In [1]:
# =========================
# БЛОК 1. Установка библиотек
# =========================

!pip install -q pandas numpy nltk spacy gensim python-Levenshtein openpyxl scikit-learn transformers torch
!python -m spacy download en_core_web_sm -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 26.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.3/153.3 kB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 40.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 48.1 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [2]:
# =========================
# БЛОК 1. Импорт библиотек
# =========================

import os
import re
import random
import warnings
from pathlib import Path
from functools import lru_cache
from typing import List, Dict, Tuple, Optional

import numpy as np
import pandas as pd

import nltk
from nltk.corpus import stopwords
from nltk.corpus import wordnet as wn

import spacy
from Levenshtein import distance as levenshtein_distance

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from google.colab import drive

warnings.filterwarnings("ignore")

nltk.download("wordnet")
nltk.download("omw-1.4")
nltk.download("stopwords")
nltk.download("punkt")

nlp = spacy.load("en_core_web_sm")
stop_words = set(stopwords.words("english"))

random.seed(42)
np.random.seed(42)

print("Библиотеки загружены.")

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

Библиотеки загружены.

In [4]:
 # =========================
# БЛОК 1. Подключение Google Drive
# =========================

drive.mount("/content/drive")

Mounted at /content/drive

In [5]:
# =========================
# БЛОК 1. Пути к файлам
# =========================

# Укажи здесь путь к папке на Google Drive, где лежат три CSV-файла.
# Пример:
# DATA_DIR = "/content/drive/MyDrive/ВКР/corpora"

DATA_DIR = "/content/drive/MyDrive/вкр"

CORPUS_FILENAME = "final_corpus .csv"
ANSWER_KEY_FILENAME = "answer_key .csv"
REALEC_FILENAME = "ege_lexical_targets_for_realec .csv"

DATA_DIR = Path(DATA_DIR)

CORPUS_PATH = DATA_DIR / CORPUS_FILENAME
ANSWER_KEY_PATH = DATA_DIR / ANSWER_KEY_FILENAME
REALEC_PATH = DATA_DIR / REALEC_FILENAME

for name, path in {
    "final_corpus": CORPUS_PATH,
    "answer_key": ANSWER_KEY_PATH,
    "REALEC": REALEC_PATH
}.items():
    print(name, "->", path, "| exists:", path.exists())

final_corpus -> /content/drive/MyDrive/вкр/final_corpus .csv | exists: True
answer_key -> /content/drive/MyDrive/вкр/answer_key .csv | exists: True
REALEC -> /content/drive/MyDrive/вкр/ege_lexical_targets_for_realec .csv | exists: True

In [6]:
# =========================
# БЛОК 1. Загрузка корпусов
# =========================

if not CORPUS_PATH.exists():
    raise FileNotFoundError(f"Не найден основной корпус: {CORPUS_PATH}")

if not ANSWER_KEY_PATH.exists():
    raise FileNotFoundError(f"Не найден answer_key: {ANSWER_KEY_PATH}")

if not REALEC_PATH.exists():
    raise FileNotFoundError(f"Не найден REALEC-файл: {REALEC_PATH}")

corpus_df = pd.read_csv(CORPUS_PATH)
answer_key_df = pd.read_csv(ANSWER_KEY_PATH)
realec_df = pd.read_csv(REALEC_PATH)

print("corpus_df:", corpus_df.shape)
print("answer_key_df:", answer_key_df.shape)
print("realec_df:", realec_df.shape)

print("\nСтолбцы corpus_df:")
print(corpus_df.columns.tolist())

print("\nСтолбцы answer_key_df:")
print(answer_key_df.columns.tolist())

print("\nСтолбцы realec_df:")
print(realec_df.columns.tolist())

corpus_df: (343, 10)
answer_key_df: (343, 7)
realec_df: (1601, 12)

Столбцы corpus_df:
['kod', 'title', 'task_id', 'distractor_1', 'distractor_2', 'distractor_3', 'target', 'full_text', 'sentence_with_gap', 'sentence_with_answer']

Столбцы answer_key_df:
['kod', 'title', 'task_id', 'distractor_1', 'distractor_2', 'distractor_3', 'target']

Столбцы realec_df:
['target_unit', 'target_head', 'correct_element', 'lexical_category', 'subcategory', 'source_target', 'error_variant', 'error_type', 'learner_sentence', 'correct_sentence', 'comment', 'source_error']

In [7]:
# =========================
# БЛОК 1. Базовая очистка текста
# =========================

def clean_text(text: str) -> str:
    """
    Приводит текст к аккуратному виду:
    - убирает NaN;
    - нормализует кавычки и тире;
    - убирает лишние пробелы.
    """
    if pd.isna(text):
        return ""

    text = str(text)
    text = text.replace("\ufeff", "")
    text = text.replace("’", "'").replace("‘", "'")
    text = text.replace("“", '"').replace("”", '"')
    text = text.replace("—", "-").replace("–", "-")
    text = re.sub(r"\s+", " ", text)

    return text.strip()


def unique_list(items: List[str]) -> List[str]:
    """
    Удаляет повторы, сохраняя исходный порядок.
    """
    result = []
    seen = set()

    for item in items:
        item = clean_text(item).lower()

        if item and item not in seen:
            result.append(item)
            seen.add(item)

    return result


def make_item_key(kod, title, task_id) -> str:
    """
    Создает уникальный идентификатор задания.
    """
    return f"{clean_text(kod)}|{clean_text(title)}|{clean_text(task_id)}"

In [8]:
# =========================
# БЛОК 1. Подготовка рабочего df
# =========================

required_columns = [
    "kod",
    "title",
    "task_id",
    "target",
    "full_text",
    "sentence_with_gap",
    "sentence_with_answer",
    "distractor_1",
    "distractor_2",
    "distractor_3"
]

missing_columns = [
    col for col in required_columns
    if col not in corpus_df.columns
]

if missing_columns:
    raise ValueError(f"В corpus_df не хватает столбцов: {missing_columns}")

df = corpus_df.copy()

df["item_key"] = df.apply(
    lambda row: make_item_key(
        row["kod"],
        row["title"],
        row["task_id"]
    ),
    axis=1
)

df["text_clean"] = df["full_text"].apply(clean_text)
df["sentence_clean"] = df["sentence_with_answer"].apply(clean_text)
df["sentence_with_gap_clean"] = df["sentence_with_gap"].apply(clean_text)
df["target_clean"] = df["target"].apply(clean_text).str.lower()

df["gold_distractors"] = df.apply(
    lambda row: unique_list([
        row["distractor_1"],
        row["distractor_2"],
        row["distractor_3"]
    ]),
    axis=1
)

print("Рабочий df:", df.shape)

df[
    [
        "kod",
        "task_id",
        "target_clean",
        "sentence_clean",
        "gold_distractors"
    ]
].head()

Рабочий df: (343, 16)

,kod,task_id,target_clean,sentence_clean,gold_distractors
0,09B13D,30,announced,"Last week, our coach Mr Brown announced we wer...","[promoted, extended, presented]"
1,09B13D,31,interested,We weren't all that interested in the outdoors.,"[delighted, inspired, excited]"
2,09B13D,32,however,"However, Mr Brown claimed that we'd really enj...","[moreover, although, otherwise]"
3,09B13D,33,thick,"Now we were in a state park, marching through ...","[heavy, strong, rich]"
4,09B13D,34,remind,"Doesn't its shape remind you of an elephant?"" ...","[review, remember, reflect]"

In [9]:
# =========================
# БЛОК 1. Быстрая диагностика корпуса
# =========================

print("Количество заданий:", len(df))
print("Пустые full_text:", df["text_clean"].eq("").sum())
print("Пустые sentence_with_answer:", df["sentence_clean"].eq("").sum())
print("Пустые sentence_with_gap:", df["sentence_with_gap_clean"].eq("").sum())
print("Пустые target:", df["target_clean"].eq("").sum())
print("Дубли item_key:", df["item_key"].duplicated().sum())

df["target_found_in_sentence"] = df.apply(
    lambda row: bool(
        re.search(
            r"\b" + re.escape(row["target_clean"]) + r"\b",
            row["sentence_clean"],
            flags=re.IGNORECASE
        )
    ),
    axis=1
)

print("Target не найден в sentence_with_answer:", (~df["target_found_in_sentence"]).sum())

df.loc[
    ~df["target_found_in_sentence"],
    ["kod", "task_id", "target_clean", "sentence_clean"]
].head(10)

Количество заданий: 343
Пустые full_text: 0
Пустые sentence_with_answer: 0
Пустые sentence_with_gap: 0
Пустые target: 0
Дубли item_key: 0
Target не найден в sentence_with_answer: 20

,kod,task_id,target_clean,sentence_clean
3,09B13D,33,thick,"Now we were in a state park, marching through ..."
14,15e618,30,recognised,Daphne recognisedthem all and stood rapt until...
16,15e618,32,tour,"After breakfast, she walked up to the castle, ..."
17,15e618,33,trouble,Changing times had continued to diminish their...
19,15e618,35,afford,The family couldn'tafford it.
38,207FE9,35,enjoy,"I unwrapped a corner of it and took a bite, pr..."
57,28EF4E,31,tell,She didn't telleither of her brothers who she ...
58,28EF4E,32,hardly,"Emily could hardlywait until her day off, and ..."
59,28EF4E,33,occupied,She had chosen her time carefully: late mornin...
60,28EF4E,34,remember,He pointed indifferently towards the red-brick...

In [10]:
# =========================
# БЛОК 1.1. Исправление склеек вокруг target
# =========================

def repair_gap_spacing(sentence_with_gap: str) -> str:
    """
    Исправляет склейки вокруг пропуска:
    33 ______as -> 33 ______ as
    word30 ______ -> word 30 ______
    """
    s = clean_text(sentence_with_gap)

    if not s:
        return ""

    s = re.sub(r"(\d{1,2}\s*_{2,})(?=[A-Za-z])", r"\1 ", s)
    s = re.sub(r"(?<=[A-Za-z])(\d{1,2}\s*_{2,})", r" \1", s)

    return clean_text(s)


def ensure_target_separated(sentence: str, target: str) -> str:
    """
    Если target склеен с соседним словом, пробуем отделить его пробелами.

    Пример:
    thickas -> thick as
    announcedwe -> announced we

    Важно: функция применяется только если target НЕ найден как отдельное слово.
    """
    s = clean_text(sentence)
    t = clean_text(target).lower()

    if not s or not t:
        return s

    exact_pattern = r"\b" + re.escape(t) + r"\b"

    if re.search(exact_pattern, s, flags=re.IGNORECASE):
        return s

    # target склеен с буквами слева и справа
    s = re.sub(
        rf"(?i)(?<=\w)({re.escape(t)})(?=\w)",
        r" \1 ",
        s
    )

    # target склеен с буквами слева
    s = re.sub(
        rf"(?i)(?<=\w)({re.escape(t)})\b",
        r" \1",
        s
    )

    # target склеен с буквами справа
    s = re.sub(
        rf"(?i)\b({re.escape(t)})(?=\w)",
        r"\1 ",
        s
    )

    return clean_text(s)


df["sentence_clean"] = df.apply(
    lambda row: ensure_target_separated(
        row["sentence_clean"],
        row["target_clean"]
    ),
    axis=1
)

df["sentence_with_gap_clean"] = df["sentence_with_gap_clean"].apply(
    repair_gap_spacing
)

df["target_found_in_sentence"] = df.apply(
    lambda row: bool(
        re.search(
            r"\b" + re.escape(row["target_clean"]) + r"\b",
            row["sentence_clean"],
            flags=re.IGNORECASE
        )
    ),
    axis=1
)

print("Target не найден после исправления:", (~df["target_found_in_sentence"]).sum())

df.loc[
    ~df["target_found_in_sentence"],
    ["kod", "task_id", "target_clean", "sentence_clean"]
].head(20)

Target не найден после исправления: 0

Empty DataFrame
Columns: [kod, task_id, target_clean, sentence_clean]
Index: []

In [11]:
# =========================
# БЛОК 2. Загрузка GloVe
# =========================

import gensim.downloader as api

GLOVE_MODEL_NAME = "glove-wiki-gigaword-100"

glove_model = api.load(GLOVE_MODEL_NAME)

print("GloVe загружена:", GLOVE_MODEL_NAME)
print("Размер словаря:", len(glove_model.key_to_index))

[==================================================] 100.0% 128.1/128.1MB downloaded
GloVe загружена: glove-wiki-gigaword-100
Размер словаря: 400000

In [12]:
# =========================
# БЛОК 2. Векторная близость
# =========================

def get_vector_for_expression(expression: str, model):
    """
    Получает вектор для слова или словосочетания.

    Если expression состоит из нескольких слов,
    берется средний вектор известных слов.
    """
    expression = clean_text(expression).lower()
    parts = expression.split()

    vectors = []

    for part in parts:
        if part in model:
            vectors.append(model[part])

    if not vectors:
        return None

    return np.mean(vectors, axis=0)


def vector_similarity(word1: str, word2: str, model) -> float:
    """
    Считает cosine similarity между target и candidate.
    """
    vec1 = get_vector_for_expression(word1, model)
    vec2 = get_vector_for_expression(word2, model)

    if vec1 is None or vec2 is None:
        return 0.0

    similarity = np.dot(vec1, vec2) / (
        np.linalg.norm(vec1) * np.linalg.norm(vec2)
    )

    return float(similarity)

In [13]:
# =========================
# БЛОК 2. Получение 50–100 семантических кандидатов
# =========================

SEMANTIC_TOPN = 100


def get_semantic_candidates(
    target: str,
    model,
    topn: int = 100
) -> List[Tuple[str, float]]:
    """
    Возвращает topn ближайших кандидатов к target по GloVe.

    На этом этапе мы НЕ решаем, хороший это дистрактор или нет.
    Мы просто собираем широкий список семантически близких слов.
    """
    target = clean_text(target).lower()

    if target not in model:
        return []

    candidates = []

    for candidate, similarity in model.most_similar(target, topn=topn):
        candidate = clean_text(candidate).lower()

        # Убираем технический мусор
        if not candidate:
            continue

        if "'" in candidate:
            continue

        if not candidate.replace("-", "").isalpha():
            continue

        candidates.append(
            (candidate, float(similarity))
        )

    return candidates

In [15]:
# =========================
# БЛОК 2. Применяем к корпусу
# =========================

df["semantic_candidates_with_scores"] = df["target_clean"].apply(
    lambda target: get_semantic_candidates(
        target,
        glove_model,
        topn=SEMANTIC_TOPN
    )
)

df["semantic_candidates"] = df["semantic_candidates_with_scores"].apply(
    lambda pairs: [candidate for candidate, score in pairs]
)

df[
    [
        "target_clean",
        "semantic_candidates"
    ]
].head(10)

  target_clean                                semantic_candidates
0    announced  [announcing, plans, announcement, announce, ag...
1   interested  [concerned, aware, talking, besides, looking, ...
2      however  [although, though, but, because, nevertheless,...
3        thick  [dense, thin, covered, tall, layer, dark, laye...
4       remind  [reminding, reminded, tell, reminds, assure, a...
5    observing  [observe, observed, monitoring, conducting, ob...
6         told  [reporters, asked, said, interview, saying, af...
7       formed  [forming, merged, established, joined, formati...
8   introduced  [adopted, introduction, originally, developed,...
9    attracted  [attracting, attracts, attract, enthusiastic, ...

In [ ]:
# =========================
# БЛОК 2. Диагностика количества кандидатов
# =========================

df["num_semantic_candidates"] = df["semantic_candidates"].apply(len)

print(df["num_semantic_candidates"].describe())

df[
    [
        "target_clean",
        "num_semantic_candidates",
        "semantic_candidates"
    ]
].head(20)

count    343.000000
mean      95.737609
std       12.628334
min        0.000000
25%       96.000000
50%       98.000000
75%      100.000000
max      100.000000
Name: num_semantic_candidates, dtype: float64

,target_clean,num_semantic_candidates,semantic_candidates
0,announced,81,"[announcing, plans, announcement, announce, ag..."
1,interested,98,"[concerned, aware, talking, besides, looking, ..."
2,however,98,"[although, though, but, because, nevertheless,..."
3,thick,98,"[dense, thin, covered, tall, layer, dark, laye..."
4,remind,99,"[reminding, reminded, tell, reminds, assure, a..."
5,observing,100,"[observe, observed, monitoring, conducting, ob..."
6,told,98,"[reporters, asked, said, interview, saying, af..."
7,formed,96,"[forming, merged, established, joined, formati..."
8,introduced,86,"[adopted, introduction, originally, developed,..."
9,attracted,100,"[attracting, attracts, attract, enthusiastic, ..."
10,out,97,"[up, put, off, back, away, into, them, just, s..."
11,talk,92,"[talking, tell, why, want, call, telling, talk..."
12,discovered,100,"[found, discovery, unearthed, revealed, believ..."
13,reason,98,"[fact, why, reasons, indeed, believe, because,..."
14,recognised,100,"[recognized, internationally, recognise, regar..."
15,imagine,93,"[maybe, remember, else, wonder, think, thing, ..."
16,tour,82,"[tours, touring, event, tournament, trip, pga,..."
17,trouble,98,"[getting, avoid, problems, difficulty, coming,..."
18,managed,100,"[manage, able, helped, failed, unable, struggl..."
19,afford,97,"[ca, pay, wo, want, willing, able, cannot, nee..."

In [ ]:
df[["target_clean", "num_semantic_candidates", "semantic_candidates"]].head(10)

,target_clean,num_semantic_candidates,semantic_candidates
0,announced,81,"[announcing, plans, announcement, announce, ag..."
1,interested,98,"[concerned, aware, talking, besides, looking, ..."
2,however,98,"[although, though, but, because, nevertheless,..."
3,thick,98,"[dense, thin, covered, tall, layer, dark, laye..."
4,remind,99,"[reminding, reminded, tell, reminds, assure, a..."
5,observing,100,"[observe, observed, monitoring, conducting, ob..."
6,told,98,"[reporters, asked, said, interview, saying, af..."
7,formed,96,"[forming, merged, established, joined, formati..."
8,introduced,86,"[adopted, introduction, originally, developed,..."
9,attracted,100,"[attracting, attracts, attract, enthusiastic, ..."

In [16]:
# =========================
# БЛОК 3. Анализ target в контексте
# =========================

def analyze_target_in_context(sentence: str, target: str) -> Dict[str, str]:
    """
    Находит target в предложении и определяет:
    - lemma: начальную форму;
    - pos: крупную часть речи, например VERB / ADJ / NOUN;
    - tag: точный грамматический тег, например VBD / VBN / JJ;
    - dep: синтаксическую роль.
    """
    sentence = clean_text(sentence)
    target = clean_text(target).lower()

    doc = nlp(sentence)

    for i, token in enumerate(doc):
        if token.text.lower() == target:
            return {
                "text": token.text.lower(),
                "lemma": token.lemma_.lower(),
                "pos": token.pos_,
                "tag": token.tag_,
                "dep": token.dep_
            }

    # Если вдруг не нашли target в предложении, анализируем само слово.
    target_doc = nlp(target)

    if len(target_doc) == 0:
        return {
            "text": target,
            "lemma": target,
            "pos": "UNKNOWN",
            "tag": "UNKNOWN",
            "dep": "UNKNOWN"
        }

    token = target_doc[0]

    return {
        "text": token.text.lower(),
        "lemma": token.lemma_.lower(),
        "pos": token.pos_,
        "tag": token.tag_,
        "dep": token.dep_
    }


df["target_analysis"] = df.apply(
    lambda row: analyze_target_in_context(
        row["sentence_clean"],
        row["target_clean"]
    ),
    axis=1
)

df["target_lemma"] = df["target_analysis"].apply(lambda x: x["lemma"])
df["target_pos"] = df["target_analysis"].apply(lambda x: x["pos"])
df["target_tag"] = df["target_analysis"].apply(lambda x: x["tag"])
df["target_dep"] = df["target_analysis"].apply(lambda x: x["dep"])

df[
    [
        "target_clean",
        "target_lemma",
        "target_pos",
        "target_tag",
        "target_dep"
    ]
].head(20)

   target_clean target_lemma target_pos target_tag target_dep
0     announced     announce       VERB        VBD       ROOT
1    interested   interested        ADJ         JJ      acomp
2       however      however        ADV         RB     advmod
3         thick        thick        ADJ         JJ     advmod
4        remind       remind       VERB         VB       ROOT
5     observing      observe       VERB        VBG       amod
6          told         tell       VERB        VBD      ccomp
7        formed         form       VERB        VBD       ROOT
8    introduced    introduce       VERB        VBD      relcl
9     attracted      attract       VERB        VBD       conj
10          out          out        ADP         RP        prt
11         talk         talk       VERB         VB       ROOT
12   discovered     discover       VERB        VBD       conj
13       reason       reason       NOUN         NN       attr
14   recognised    recognise       VERB        VBD       ROOT
15      imagine      imagine       VERB         VB       ROOT
16         tour         tour       NOUN         NN       pobj
17      trouble      trouble       NOUN         NN       pobj
18      managed       manage       VERB        VBD       ROOT
19       afford       afford       VERB         VB       ROOT

In [17]:
# =========================
# БЛОК 3. Анализ кандидата
# =========================

@lru_cache(maxsize=50000)
def cached_word_analysis(word: str) -> Tuple[str, str, str]:
    """
    Быстрый анализ отдельного слова:
    возвращает lemma, pos, tag.
    """
    word = clean_text(word).lower()
    doc = nlp(word)

    if len(doc) == 0:
        return word, "UNKNOWN", "UNKNOWN"

    token = doc[0]

    return token.lemma_.lower(), token.pos_, token.tag_


def get_candidate_lemma(candidate: str) -> str:
    return cached_word_analysis(candidate)[0]


def get_candidate_pos(candidate: str) -> str:
    return cached_word_analysis(candidate)[1]


def get_candidate_tag(candidate: str) -> str:
    return cached_word_analysis(candidate)[2]

In [22]:
# =========================
# БЛОК 3. Грамматические группы
# =========================

DISCOURSE_MARKERS = {
    "however", "although", "though", "therefore", "moreover",
    "nevertheless", "otherwise", "instead", "meanwhile", "besides"
}

PREPOSITIONS_AND_PARTICLES = {
    "in", "on", "at", "by", "for", "from", "with", "into", "onto",
    "out", "up", "off", "away", "back", "down", "over", "around"
}


def get_form_group(word: str, pos: str, tag: str) -> str:
    """
    Переводит pos/tag в более полезную для ЕГЭ грамматическую группу.
    """
    word = clean_text(word).lower()

    if word in DISCOURSE_MARKERS:
        return "discourse_marker"

    if word in PREPOSITIONS_AND_PARTICLES:
        return "preposition_or_particle"

    # announced, told, formed
    if tag == "VBD":
        return "verb_past"

    # interested, disappointed, introduced
    if tag == "VBN":
        return "participle_past"

    # observing, looking, thinking
    if tag == "VBG":
        return "participle_ing"

    # happy, thick, important
    if tag in {"JJ", "JJR", "JJS"}:
        # Если слово выглядит как причастие, лучше считать его participial adjective.
        if word.endswith("ed") or word.endswith("en"):
            return "participle_past"
        if word.endswith("ing"):
            return "participle_ing"
        return "adjective"

    # however часто может быть RB
    if tag in {"RB", "RBR", "RBS"}:
        if word in DISCOURSE_MARKERS:
            return "discourse_marker"
        return "adverb"

    if pos == "NOUN":
        return "noun"

    if pos == "VERB":
        return "verb"

    return pos.lower()

In [23]:
# =========================
# БЛОК 3. Группа target
# =========================

df["target_form_group"] = df.apply(
    lambda row: get_form_group(
        row["target_clean"],
        row["target_pos"],
        row["target_tag"]
    ),
    axis=1
)

df[
    [
        "target_clean",
        "target_pos",
        "target_tag",
        "target_form_group"
    ]
].head(20)

   target_clean target_pos target_tag        target_form_group
0     announced       VERB        VBD                verb_past
1    interested        ADJ         JJ          participle_past
2       however        ADV         RB         discourse_marker
3         thick        ADJ         JJ                adjective
4        remind       VERB         VB                     verb
5     observing       VERB        VBG           participle_ing
6          told       VERB        VBD                verb_past
7        formed       VERB        VBD                verb_past
8    introduced       VERB        VBD                verb_past
9     attracted       VERB        VBD                verb_past
10          out        ADP         RP  preposition_or_particle
11         talk       VERB         VB                     verb
12   discovered       VERB        VBD                verb_past
13       reason       NOUN         NN                     noun
14   recognised       VERB        VBD                verb_past
15      imagine       VERB         VB                     verb
16         tour       NOUN         NN                     noun
17      trouble       NOUN         NN                     noun
18      managed       VERB        VBD                verb_past
19       afford       VERB         VB                     verb

In [24]:
# =========================
# БЛОК 3. Грамматическая совместимость candidate и target
# =========================

def is_same_lemma(candidate: str, target: str) -> bool:
    """
    Проверяет, не является ли кандидат формой того же слова.
    Например:
    announce / announced / announcing
    remind / reminded / reminding
    """
    candidate = clean_text(candidate).lower()
    target = clean_text(target).lower()

    return get_candidate_lemma(candidate) == get_candidate_lemma(target)


def candidate_form_group(candidate: str) -> str:
    """
    Определяет грамматическую группу кандидата.
    """
    candidate = clean_text(candidate).lower()

    lemma, pos, tag = cached_word_analysis(candidate)

    return get_form_group(candidate, pos, tag)


def is_grammar_compatible(candidate: str, row) -> bool:
    """
    Проверяет, подходит ли candidate по грамматической форме к target.
    """
    candidate = clean_text(candidate).lower()
    target = row["target_clean"]

    if not candidate or candidate == target:
        return False

    if is_same_lemma(candidate, target):
        return False

    target_group = row["target_form_group"]
    candidate_group = candidate_form_group(candidate)

    # however -> therefore / moreover / otherwise
    if target_group == "discourse_marker":
        return candidate_group == "discourse_marker"

    # out -> off / up / away
    if target_group == "preposition_or_particle":
        return candidate_group == "preposition_or_particle"

    # interested -> excited / delighted / inspired
    if target_group == "participle_past":
        return candidate_group == "participle_past"

    # observing -> monitoring / conducting / analyzing
    if target_group == "participle_ing":
        return candidate_group == "participle_ing"

    # announced / told / formed
    if target_group == "verb_past":
        return candidate_group in {"verb_past", "participle_past"}

    # thick / happy / important
    if target_group == "adjective":
        return candidate_group == "adjective"

    # reason / tour / trouble
    if target_group == "noun":
        return candidate_group == "noun"

    # remind / imagine / afford
    if target_group == "verb":
        return candidate_group == "verb"

    # definitely
    if target_group == "adverb":
        return candidate_group == "adverb"

    return candidate_group == target_group

In [27]:
df["num_semantic_candidates"] = df["semantic_candidates"].apply(len)

In [28]:
# =========================
# БЛОК 3. Применяем грамматический фильтр
# =========================

df["semantic_candidates_grammar"] = df.apply(
    lambda row: [
        candidate
        for candidate in row["semantic_candidates"]
        if is_grammar_compatible(candidate, row)
    ],
    axis=1
)

df["num_semantic_candidates_grammar"] = df["semantic_candidates_grammar"].apply(len)

df[
    [
        "target_clean",
        "target_form_group",
        "num_semantic_candidates",
        "num_semantic_candidates_grammar",
        "semantic_candidates_grammar"
    ]
].head(20)

,target_clean,target_form_group,num_semantic_candidates,num_semantic_candidates_grammar,semantic_candidates_grammar
0,announced,verb_past,81,20,"[agreed, planned, decided, expected, unveiled,..."
1,interested,participle_past,98,3,"[involved, keen, realized]"
2,however,discourse_marker,98,6,"[although, though, nevertheless, therefore, mo..."
3,thick,adjective,98,25,"[dense, thin, tall, dark, yellow, dry, shiny, ..."
4,remind,verb,99,42,"[tell, ask, forget, wish, inform, remember, im..."
5,observing,participle_ing,100,58,"[monitoring, conducting, analyzing, photograph..."
6,told,verb_past,98,33,"[asked, said, quoted, insisted, spoke, informe..."
7,formed,verb_past,96,30,"[merged, established, joined, created, founded..."
8,introduced,verb_past,86,29,"[adopted, developed, created, modified, used, ..."
9,attracted,verb_past,100,19,"[drew, garnered, encouraged, generated, grew, ..."
10,out,preposition_or_particle,97,11,"[up, off, back, away, into, down, over, with, ..."
11,talk,verb,92,31,"[tell, want, call, think, listen, know, come, ..."
12,discovered,verb_past,100,45,"[found, unearthed, revealed, believed, identif..."
13,reason,noun,98,11,"[fact, question, thing, idea, sense, sort, ins..."
14,recognised,verb_past,100,34,"[recognized, regarded, established, respected,..."
15,imagine,verb,93,25,"[remember, think, forget, know, tell, guess, f..."
16,tour,noun,82,39,"[event, tournament, trip, weekend, track, stag..."
17,trouble,noun,98,13,"[problems, difficulty, problem, lot, difficult..."
18,managed,verb_past,100,27,"[helped, failed, struggled, allowed, went, wor..."
19,afford,verb,97,51,"[pay, want, need, do, lose, spend, make, expec..."

In [29]:
# =========================
# БЛОК 3. Диагностика после грамматического фильтра
# =========================

for _, row in df.head(12).iterrows():
    print("=" * 100)
    print("target:", row["target_clean"])
    print("target_group:", row["target_form_group"])
    print("до фильтра:", row["semantic_candidates"][:15])
    print("после фильтра:", row["semantic_candidates_grammar"][:15])

====================================================================================================
target: announced
target_group: verb_past
до фильтра: ['announcing', 'plans', 'announcement', 'announce', 'agreed', 'recently', 'tuesday', 'thursday', 'wednesday', 'monday', 'month', 'earlier', 'planned', 'decided', 'week']
после фильтра: ['agreed', 'planned', 'decided', 'expected', 'unveiled', 'proposed', 'confirmed', 'approved', 'promised', 'scheduled', 'signed', 'rejected', 'issued', 'launched', 'offered']
====================================================================================================
target: interested
target_group: participle_past
до фильтра: ['concerned', 'aware', 'talking', 'besides', 'looking', 'thinking', 'focused', 'doing', 'discussing', 'wanting', 'studying', 'involved', 'idea', 'consider', 'considering']
после фильтра: ['involved', 'keen', 'realized']
====================================================================================================
target: however
target_group: discourse_marker
до фильтра: ['although', 'though', 'but', 'because', 'nevertheless', 'only', 'result', 'that', 'not', 'this', 'yet', 'fact', 'later', 'as', 'both']
после фильтра: ['although', 'though', 'nevertheless', 'therefore', 'moreover', 'instead']
====================================================================================================
target: thick
target_group: adjective
до фильтра: ['dense', 'thin', 'covered', 'tall', 'layer', 'dark', 'layers', 'thicker', 'inch', 'beneath', 'clouds', 'yellow', 'diameter', 'sand', 'coated']
после фильтра: ['dense', 'thin', 'tall', 'dark', 'yellow', 'dry', 'shiny', 'deep', 'rough', 'gray', 'large', 'sturdy', 'shallow', 'soft', 'heavy']
====================================================================================================
target: remind
target_group: verb
до фильтра: ['reminding', 'reminded', 'tell', 'reminds', 'assure', 'ask', 'forget', 'wish', 'inform', 'remember', 'impress', 'inspire', 'everyone', 'surely', 'let']
после фильтра: ['tell', 'ask', 'forget', 'wish', 'inform', 'remember', 'impress', 'let', 'educate', 'motivate', 'understand', 'thank', 'want', 'listen', 'imagine']
====================================================================================================
target: observing
target_group: participle_ing
до фильтра: ['observe', 'observed', 'monitoring', 'conducting', 'observation', 'analyzing', 'monitor', 'photographing', 'keeping', 'witnessing', 'cease', 'guiding', 'tracking', 'watching', 'studying']
после фильтра: ['monitoring', 'conducting', 'analyzing', 'photographing', 'keeping', 'witnessing', 'guiding', 'tracking', 'watching', 'studying', 'surveying', 'simulating', 'evaluating', 'setting', 'analysing']
====================================================================================================
target: told
target_group: verb_past
до фильтра: ['reporters', 'asked', 'said', 'interview', 'saying', 'afp', 'quoted', 'insisted', 'telling', 'spoke', 'statement', 'informed', 'press', 'speaking', 'explained']
после фильтра: ['asked', 'said', 'quoted', 'insisted', 'spoke', 'informed', 'explained', 'met', 'acknowledged', 'warned', 'suggested', 'did', 'wanted', 'talked', 'noted']
====================================================================================================
target: formed
target_group: verb_past
до фильтра: ['forming', 'merged', 'established', 'joined', 'formation', 'created', 'founded', 'incorporated', 'split', 'form', 'group', 'member', 'became', 'newly', 'members']
после фильтра: ['merged', 'established', 'joined', 'created', 'founded', 'incorporated', 'became', 'called', 'known', 'composed', 'renamed', 'began', 'led', 'disbanded', 'developed']
====================================================================================================
target: introduced
target_group: verb_past
до фильтра: ['adopted', 'introduction', 'originally', 'developed', 'created', 'version', 'introducing', 'introduce', 'similar', 'modified', 'later', 'recently', 'used', 'changed', 'proposed']
после фильтра: ['adopted', 'developed', 'created', 'modified', 'used', 'changed', 'proposed', 'designed', 'replaced', 'called', 'expanded', 'included', 'passed', 'became', 'implemented']
====================================================================================================
target: attracted
target_group: verb_past
до фильтра: ['attracting', 'attracts', 'attract', 'enthusiastic', 'attention', 'audiences', 'drew', 'among', 'audience', 'garnered', 'particularly', 'draws', 'encouraged', 'generated', 'amongst']
после фильтра: ['drew', 'garnered', 'encouraged', 'generated', 'grew', 'grown', 'spurred', 'devoted', 'brought', 'enjoyed', 'turned', 'drawn', 'aroused', 'seen', 'impressed']
====================================================================================================
target: out
target_group: preposition_or_particle
до фильтра: ['up', 'put', 'off', 'back', 'away', 'into', 'them', 'just', 'so', 'get', 'down', 'all', 'way', 'but', 'going']
после фильтра: ['up', 'off', 'back', 'away', 'into', 'down', 'over', 'with', 'on', 'from', 'around']
====================================================================================================
target: talk
target_group: verb
до фильтра: ['talking', 'tell', 'why', 'want', 'call', 'telling', 'talked', 'think', 'listen', 'know', 'come', 'you', 'me', 'going', 'hear']
после фильтра: ['tell', 'want', 'call', 'think', 'listen', 'know', 'come', 'hear', 'do', 'go', 'let', 'get', 'ask', 'answer', 'see']

In [30]:
# =========================
# БЛОК 4. Проверка появления кандидата в тексте
# =========================

def appears_as_word(candidate: str, text: str) -> bool:
    """
    Проверяет, встречается ли candidate в тексте как отдельное слово.

    Например:
    candidate = "talk"
    text = "talking" -> False
    text = "talk to me" -> True
    """
    candidate = clean_text(candidate).lower()
    text = clean_text(text).lower()

    if not candidate or not text:
        return False

    pattern = r"\b" + re.escape(candidate) + r"\b"

    return bool(
        re.search(
            pattern,
            text,
            flags=re.IGNORECASE
        )
    )


def is_allowed_stopword_candidate(candidate: str, row) -> bool:
    """
    Обычно стоп-слова плохие кандидаты.

    Но если target сам является предлогом / частицей,
    то кандидаты тоже могут быть служебными словами:
    out -> off / up / away
    at -> in / on / by
    """
    candidate = clean_text(candidate).lower()
    target_group = row["target_form_group"]

    if candidate not in stop_words:
        return True

    if target_group in {
        "preposition_or_particle",
        "discourse_marker"
    }:
        return True

    return False

In [31]:
# =========================
# БЛОК 4. Причина удаления по контексту
# =========================

def context_filter_reason(candidate: str, row) -> Optional[str]:
    """
    Возвращает причину, почему кандидат нужно удалить.
    Если кандидат можно оставить, возвращает None.
    """
    candidate = clean_text(candidate).lower()

    if not candidate:
        return "empty_candidate"

    if not is_allowed_stopword_candidate(candidate, row):
        return "stopword"

    if appears_as_word(candidate, row["sentence_clean"]):
        return "candidate_already_in_sentence"

    if appears_as_word(candidate, row["text_clean"]):
        return "candidate_already_in_full_text"

    return None


def apply_context_filter(row) -> List[str]:
    """
    Оставляет только кандидатов, которые не встречаются
    в предложении и полном тексте.
    """
    result = []

    for candidate in row["semantic_candidates_grammar"]:
        reason = context_filter_reason(candidate, row)

        if reason is None:
            result.append(candidate)

    return unique_list(result)


def collect_removed_by_context(row) -> List[Dict[str, str]]:
    """
    Сохраняет удаленные кандидаты и причину удаления.
    Это полезно для диагностики и описания в ВКР.
    """
    removed = []

    for candidate in row["semantic_candidates_grammar"]:
        reason = context_filter_reason(candidate, row)

        if reason is not None:
            removed.append(
                {
                    "candidate": candidate,
                    "reason": reason
                }
            )

    return removed

In [33]:
# =========================
# БЛОК 4. Применяем контекстный фильтр
# =========================

df["semantic_candidates_context"] = df.apply(
    apply_context_filter,
    axis=1
)

df["removed_by_context_filter"] = df.apply(
    collect_removed_by_context,
    axis=1
)

df["num_semantic_candidates_context"] = df["semantic_candidates_context"].apply(len)

df[
    [
        "target_clean",
        "target_form_group",
        "num_semantic_candidates_grammar",
        "num_semantic_candidates_context",
        "semantic_candidates_context"
    ]
].head(20)

,target_clean,target_form_group,num_semantic_candidates_grammar,num_semantic_candidates_context,semantic_candidates_context
0,announced,verb_past,20,20,"[agreed, planned, decided, expected, unveiled,..."
1,interested,participle_past,3,3,"[involved, keen, realized]"
2,however,discourse_marker,6,6,"[although, though, nevertheless, therefore, mo..."
3,thick,adjective,25,25,"[dense, thin, tall, dark, yellow, dry, shiny, ..."
4,remind,verb,42,41,"[tell, ask, forget, wish, inform, remember, im..."
5,observing,participle_ing,58,57,"[monitoring, conducting, analyzing, photograph..."
6,told,verb_past,33,30,"[asked, said, quoted, insisted, spoke, informe..."
7,formed,verb_past,30,27,"[merged, established, joined, created, founded..."
8,introduced,verb_past,29,27,"[adopted, created, modified, used, changed, pr..."
9,attracted,verb_past,19,17,"[drew, garnered, encouraged, generated, grew, ..."
10,out,preposition_or_particle,11,10,"[up, off, back, away, into, down, over, on, fr..."
11,talk,verb,31,27,"[tell, want, call, listen, know, come, hear, g..."
12,discovered,verb_past,45,37,"[unearthed, revealed, believed, identified, de..."
13,reason,noun,11,10,"[fact, question, thing, idea, sort, instance, ..."
14,recognised,verb_past,34,34,"[recognized, regarded, established, respected,..."
15,imagine,verb,25,23,"[remember, think, forget, know, tell, guess, f..."
16,tour,noun,39,35,"[event, tournament, trip, weekend, track, stag..."
17,trouble,noun,13,12,"[problems, difficulty, problem, lot, difficult..."
18,managed,verb_past,27,23,"[helped, failed, struggled, allowed, worked, t..."
19,afford,verb,51,49,"[pay, want, need, lose, spend, make, expect, g..."

In [35]:
# =========================
# БЛОК 4. Диагностика после контекстной фильтрации
# =========================

for _, row in df.head(20).iterrows():
    print("=" * 100)
    print("target:", row["target_clean"])
    print("target_group:", row["target_form_group"])
    print("после грамматики:", row["semantic_candidates_grammar"][:15])
    print("после контекста:", row["semantic_candidates_context"][:15])
    print("удалено:", row["removed_by_context_filter"][:8])

====================================================================================================
target: announced
target_group: verb_past
после грамматики: ['agreed', 'planned', 'decided', 'expected', 'unveiled', 'proposed', 'confirmed', 'approved', 'promised', 'scheduled', 'signed', 'rejected', 'issued', 'launched', 'offered']
после контекста: ['agreed', 'planned', 'decided', 'expected', 'unveiled', 'proposed', 'confirmed', 'approved', 'promised', 'scheduled', 'signed', 'rejected', 'issued', 'launched', 'offered']
удалено: []
====================================================================================================
target: interested
target_group: participle_past
после грамматики: ['involved', 'keen', 'realized']
после контекста: ['involved', 'keen', 'realized']
удалено: []
====================================================================================================
target: however
target_group: discourse_marker
после грамматики: ['although', 'though', 'nevertheless', 'therefore', 'moreover', 'instead']
после контекста: ['although', 'though', 'nevertheless', 'therefore', 'moreover', 'instead']
удалено: []
====================================================================================================
target: thick
target_group: adjective
после грамматики: ['dense', 'thin', 'tall', 'dark', 'yellow', 'dry', 'shiny', 'deep', 'rough', 'gray', 'large', 'sturdy', 'shallow', 'soft', 'heavy']
после контекста: ['dense', 'thin', 'tall', 'dark', 'yellow', 'dry', 'shiny', 'deep', 'rough', 'gray', 'large', 'sturdy', 'shallow', 'soft', 'heavy']
удалено: []
====================================================================================================
target: remind
target_group: verb
после грамматики: ['tell', 'ask', 'forget', 'wish', 'inform', 'remember', 'impress', 'let', 'educate', 'motivate', 'understand', 'thank', 'want', 'listen', 'imagine']
после контекста: ['tell', 'ask', 'forget', 'wish', 'inform', 'remember', 'impress', 'let', 'educate', 'motivate', 'understand', 'thank', 'want', 'listen', 'imagine']
удалено: [{'candidate': 'do', 'reason': 'stopword'}]
====================================================================================================
target: observing
target_group: participle_ing
после грамматики: ['monitoring', 'conducting', 'analyzing', 'photographing', 'keeping', 'witnessing', 'guiding', 'tracking', 'watching', 'studying', 'surveying', 'simulating', 'evaluating', 'setting', 'analysing']
после контекста: ['monitoring', 'conducting', 'analyzing', 'photographing', 'keeping', 'witnessing', 'guiding', 'tracking', 'watching', 'studying', 'surveying', 'simulating', 'evaluating', 'setting', 'analysing']
удалено: [{'candidate': 'doing', 'reason': 'stopword'}]
====================================================================================================
target: told
target_group: verb_past
после грамматики: ['asked', 'said', 'quoted', 'insisted', 'spoke', 'informed', 'explained', 'met', 'acknowledged', 'warned', 'suggested', 'did', 'wanted', 'talked', 'noted']
после контекста: ['asked', 'said', 'quoted', 'insisted', 'spoke', 'informed', 'explained', 'met', 'acknowledged', 'warned', 'suggested', 'wanted', 'talked', 'noted', 'added']
удалено: [{'candidate': 'did', 'reason': 'stopword'}, {'candidate': 'replied', 'reason': 'candidate_already_in_full_text'}, {'candidate': 'had', 'reason': 'stopword'}]
====================================================================================================
target: formed
target_group: verb_past
после грамматики: ['merged', 'established', 'joined', 'created', 'founded', 'incorporated', 'became', 'called', 'known', 'composed', 'renamed', 'began', 'led', 'disbanded', 'developed']
после контекста: ['merged', 'established', 'joined', 'created', 'founded', 'incorporated', 'became', 'called', 'known', 'composed', 'renamed', 'began', 'led', 'disbanded', 'organized']
удалено: [{'candidate': 'developed', 'reason': 'candidate_already_in_full_text'}, {'candidate': 'was', 'reason': 'stopword'}, {'candidate': 'been', 'reason': 'stopword'}]
====================================================================================================
target: introduced
target_group: verb_past
после грамматики: ['adopted', 'developed', 'created', 'modified', 'used', 'changed', 'proposed', 'designed', 'replaced', 'called', 'expanded', 'included', 'passed', 'became', 'implemented']
после контекста: ['adopted', 'created', 'modified', 'used', 'changed', 'proposed', 'designed', 'replaced', 'called', 'expanded', 'included', 'passed', 'became', 'implemented', 'incorporated']
удалено: [{'candidate': 'developed', 'reason': 'candidate_already_in_full_text'}, {'candidate': 'was', 'reason': 'stopword'}]
====================================================================================================
target: attracted
target_group: verb_past
после грамматики: ['drew', 'garnered', 'encouraged', 'generated', 'grew', 'grown', 'spurred', 'devoted', 'brought', 'enjoyed', 'turned', 'drawn', 'aroused', 'seen', 'impressed']
после контекста: ['drew', 'garnered', 'encouraged', 'generated', 'grew', 'grown', 'spurred', 'devoted', 'brought', 'enjoyed', 'drawn', 'aroused', 'seen', 'impressed', 'received']
удалено: [{'candidate': 'turned', 'reason': 'candidate_already_in_full_text'}, {'candidate': 'interested', 'reason': 'candidate_already_in_full_text'}]
====================================================================================================
target: out
target_group: preposition_or_particle
после грамматики: ['up', 'off', 'back', 'away', 'into', 'down', 'over', 'with', 'on', 'from', 'around']
после контекста: ['up', 'off', 'back', 'away', 'into', 'down', 'over', 'on', 'from', 'around']
удалено: [{'candidate': 'with', 'reason': 'candidate_already_in_full_text'}]
====================================================================================================
target: talk
target_group: verb
после грамматики: ['tell', 'want', 'call', 'think', 'listen', 'know', 'come', 'hear', 'do', 'go', 'let', 'get', 'ask', 'answer', 'see']
после контекста: ['tell', 'want', 'call', 'listen', 'know', 'come', 'hear', 'go', 'let', 'get', 'ask', 'answer', 'see', 'show', 'mind']
удалено: [{'candidate': 'think', 'reason': 'candidate_already_in_full_text'}, {'candidate': 'do', 'reason': 'stopword'}, {'candidate': 'does', 'reason': 'stopword'}, {'candidate': 'make', 'reason': 'candidate_already_in_full_text'}]
====================================================================================================
target: discovered
target_group: verb_past
после грамматики: ['found', 'unearthed', 'revealed', 'believed', 'identified', 'detected', 'uncovered', 'excavated', 'been', 'traced', 'buried', 'examined', 'recovered', 'taken', 'had']
после контекста: ['unearthed', 'revealed', 'believed', 'identified', 'detected', 'uncovered', 'excavated', 'traced', 'buried', 'examined', 'recovered', 'taken', 'disappeared', 'described', 'noticed']
удалено: [{'candidate': 'found', 'reason': 'candidate_already_in_full_text'}, {'candidate': 'been', 'reason': 'stopword'}, {'candidate': 'had', 'reason': 'stopword'}, {'candidate': 'died', 'reason': 'candidate_already_in_full_text'}, {'candidate': 'was', 'reason': 'stopword'}, {'candidate': 'were', 'reason': 'stopword'}, {'candidate': 'turned', 'reason': 'candidate_already_in_full_text'}, {'candidate': 'developed', 'reason': 'candidate_already_in_full_text'}]
====================================================================================================
target: reason
target_group: noun
после грамматики: ['fact', 'question', 'thing', 'idea', 'sense', 'sort', 'instance', 'explanation', 'possibility', 'example', 'notion']
после контекста: ['fact', 'question', 'thing', 'idea', 'sort', 'instance', 'explanation', 'possibility', 'example', 'notion']
удалено: [{'candidate': 'sense', 'reason': 'candidate_already_in_full_text'}]
====================================================================================================
target: recognised
target_group: verb_past
после грамматики: ['recognized', 'regarded', 'established', 'respected', 'accepted', 'considered', 'governed', 'conferred', 'honoured', 'accredited', 'declared', 'bestowed', 'achieved', 'chosen', 'granted']
после контекста: ['recognized', 'regarded', 'established', 'respected', 'accepted', 'considered', 'governed', 'conferred', 'honoured', 'accredited', 'declared', 'bestowed', 'achieved', 'chosen', 'granted']
удалено: []
====================================================================================================
target: imagine
target_group: verb
после грамматики: ['remember', 'think', 'forget', 'know', 'tell', 'guess', 'feel', 'understand', 'realize', 'happen', 'mind', 'want', 'happens', 'do', 'see']
после контекста: ['remember', 'think', 'forget', 'know', 'tell', 'guess', 'feel', 'understand', 'realize', 'happen', 'mind', 'want', 'happens', 'pretend', 'hear']
удалено: [{'candidate': 'do', 'reason': 'stopword'}, {'candidate': 'see', 'reason': 'candidate_already_in_full_text'}]
====================================================================================================
target: tour
target_group: noun
после грамматики: ['event', 'tournament', 'trip', 'weekend', 'track', 'stage', 'tournaments', 'world', 'golf', 'championship', 'cycling', 'summer', 'team', 'day', 'course']
после контекста: ['event', 'tournament', 'trip', 'weekend', 'track', 'stage', 'tournaments', 'golf', 'championship', 'cycling', 'summer', 'team', 'day', 'course', 'year']
удалено: [{'candidate': 'world', 'reason': 'candidate_already_in_full_text'}, {'candidate': 'time', 'reason': 'candidate_already_in_full_text'}, {'candidate': 'place', 'reason': 'candidate_already_in_full_text'}, {'candidate': 'part', 'reason': 'candidate_already_in_full_text'}]
====================================================================================================
target: trouble
target_group: noun
после грамматики: ['problems', 'difficulty', 'problem', 'lot', 'difficulties', 'chance', 'time', 'things', 'possibility', 'weeks', 'reason', 'danger', 'job']
после контекста: ['problems', 'difficulty', 'problem', 'lot', 'difficulties', 'chance', 'things', 'possibility', 'weeks', 'reason', 'danger', 'job']
удалено: [{'candidate': 'time', 'reason': 'candidate_already_in_full_text'}]
====================================================================================================
target: managed
target_group: verb_past
после грамматики: ['helped', 'failed', 'struggled', 'allowed', 'went', 'worked', 'took', 'tried', 'taken', 'had', 'set', 'saw', 'needed', 'did', 'decided']
после контекста: ['helped', 'failed', 'struggled', 'allowed', 'worked', 'took', 'tried', 'taken', 'set', 'saw', 'needed', 'decided', 'secured', 'lost', 'forced']
удалено: [{'candidate': 'went', 'reason': 'candidate_already_in_full_text'}, {'candidate': 'had', 'reason': 'stopword'}, {'candidate': 'did', 'reason': 'stopword'}, {'candidate': 'continued', 'reason': 'candidate_already_in_full_text'}]
====================================================================================================
target: afford
target_group: verb
после грамматики: ['pay', 'want', 'need', 'do', 'lose', 'spend', 'make', 'expect', 'get', 'rely', 'prefer', 'buy', 'fail', 'borrow', 'realize']
после контекста: ['pay', 'want', 'need', 'lose', 'spend', 'make', 'expect', 'get', 'rely', 'prefer', 'buy', 'fail', 'borrow', 'realize', 'worry']
удалено: [{'candidate': 'do', 'reason': 'stopword'}, {'candidate': 'does', 'reason': 'stopword'}]

In [36]:
# =========================
# БЛОК 5. WordNet: синонимы и антонимы
# =========================

def spacy_pos_to_wordnet(pos: str):
    """
    Переводит spaCy POS в WordNet POS.
    """
    mapping = {
        "NOUN": wn.NOUN,
        "VERB": wn.VERB,
        "ADJ": wn.ADJ,
        "ADV": wn.ADV
    }

    return mapping.get(pos)


def get_wordnet_synonyms(word: str, pos: str) -> set:
    """
    Возвращает прямые синонимы слова из WordNet.
    """
    word = clean_text(word).lower()
    wn_pos = spacy_pos_to_wordnet(pos)

    if wn_pos is None:
        return set()

    synonyms = set()

    for synset in wn.synsets(word, pos=wn_pos):
        for lemma in synset.lemmas():
            synonyms.add(
                lemma.name()
                .replace("_", " ")
                .lower()
            )

    synonyms.discard(word)

    return synonyms


def share_wordnet_synset(word1: str, word2: str, pos: str) -> bool:
    """
    Проверяет, находятся ли два слова в одном WordNet-синсете.
    Это сильный признак почти-эквивалентности.
    """
    wn_pos = spacy_pos_to_wordnet(pos)

    if wn_pos is None:
        return False

    synsets1 = set(
        wn.synsets(
            clean_text(word1).lower(),
            pos=wn_pos
        )
    )

    synsets2 = set(
        wn.synsets(
            clean_text(word2).lower(),
            pos=wn_pos
        )
    )

    return bool(synsets1 & synsets2)


def get_wordnet_antonyms(word: str, pos: str) -> set:
    """
    Возвращает антонимы слова из WordNet.
    """
    word = clean_text(word).lower()
    wn_pos = spacy_pos_to_wordnet(pos)

    if wn_pos is None:
        return set()

    antonyms = set()

    for synset in wn.synsets(word, pos=wn_pos):
        for lemma in synset.lemmas():
            for antonym in lemma.antonyms():
                antonyms.add(
                    antonym.name()
                    .replace("_", " ")
                    .lower()
                )

    return antonyms


def is_antonym_candidate(candidate: str, target: str, target_pos: str) -> bool:
    """
    Проверяет, является ли candidate антонимом target.
    """
    candidate = clean_text(candidate).lower()
    target = clean_text(target).lower()

    return (
        candidate in get_wordnet_antonyms(target, target_pos)
        or target in get_wordnet_antonyms(candidate, target_pos)
    )

In [37]:
# =========================
# БЛОК 5. Ручные группы полярности
# =========================

POSITIVE_EMOTION_WORDS = {
    "happy", "glad", "pleased", "delighted", "excited",
    "satisfied", "confident", "relaxed", "proud", "cheerful",
    "joyful", "thrilled", "content", "grateful", "hopeful",
    "calm", "interested", "inspired", "enthusiastic"
}

NEGATIVE_EMOTION_WORDS = {
    "sad", "angry", "tired", "disappointed", "frustrated",
    "confused", "upset", "worried", "afraid", "anxious",
    "nervous", "shocked", "depressed", "annoyed", "bored",
    "guilty", "unhappy"
}


def get_emotion_polarity(word: str) -> Optional[str]:
    """
    Возвращает positive / negative для эмоциональной лексики.
    """
    word = clean_text(word).lower()

    if word in POSITIVE_EMOTION_WORDS:
        return "positive"

    if word in NEGATIVE_EMOTION_WORDS:
        return "negative"

    return None


def has_opposite_emotion_polarity(candidate: str, target: str) -> bool:
    """
    Убирает пары типа:
    disappointed -> delighted
    happy -> sad

    Они часто слишком очевидные и не подходят как качественные дистракторы.
    """
    candidate_polarity = get_emotion_polarity(candidate)
    target_polarity = get_emotion_polarity(target)

    return (
        candidate_polarity is not None
        and target_polarity is not None
        and candidate_polarity != target_polarity
    )

In [38]:
# =========================
# БЛОК 5. Фильтр почти-эквивалентов
# =========================

MAX_ALLOWED_VECTOR_SIMILARITY = 0.82


def near_equivalent_reason(candidate: str, row) -> Optional[str]:
    """
    Возвращает причину удаления кандидата,
    если он слишком близок к target.
    """
    candidate = clean_text(candidate).lower()
    target = row["target_clean"]
    target_pos = row["target_pos"]

    similarity = vector_similarity(
        target,
        candidate,
        glove_model
    )

    # Прямой синоним WordNet
    if candidate in get_wordnet_synonyms(target, target_pos):
        return "wordnet_synonym"

    # То же значение в WordNet
    if share_wordnet_synset(candidate, target, target_pos):
        return "same_wordnet_synset"

    # Антоним
    if is_antonym_candidate(candidate, target, target_pos):
        return "wordnet_antonym"

    # Противоположная эмоциональная полярность
    if has_opposite_emotion_polarity(candidate, target):
        return "opposite_emotion_polarity"

    # Слишком высокая векторная близость
    if similarity > MAX_ALLOWED_VECTOR_SIMILARITY:
        return "too_high_vector_similarity"

    return None


def apply_near_equivalent_filter(row) -> List[str]:
    """
    Убирает кандидаты, которые слишком близки к target
    или являются очевидными антонимами.
    """
    result = []

    for candidate in row["semantic_candidates_context"]:
        reason = near_equivalent_reason(candidate, row)

        if reason is None:
            result.append(candidate)

    return unique_list(result)


def collect_removed_by_near_equivalent_filter(row) -> List[Dict[str, str]]:
    """
    Сохраняет удаленные кандидаты и причину.
    """
    removed = []

    for candidate in row["semantic_candidates_context"]:
        reason = near_equivalent_reason(candidate, row)

        if reason is not None:
            removed.append(
                {
                    "candidate": candidate,
                    "reason": reason,
                    "similarity": round(
                        vector_similarity(
                            row["target_clean"],
                            candidate,
                            glove_model
                        ),
                        4
                    )
                }
            )

    return removed

In [39]:
# =========================
# БЛОК 5. Применяем фильтр почти-эквивалентов
# =========================

df["semantic_candidates_clean"] = df.apply(
    apply_near_equivalent_filter,
    axis=1
)

df["removed_by_near_equivalent_filter"] = df.apply(
    collect_removed_by_near_equivalent_filter,
    axis=1
)

df["num_semantic_candidates_clean"] = df["semantic_candidates_clean"].apply(len)

df[
    [
        "target_clean",
        "num_semantic_candidates_context",
        "num_semantic_candidates_clean",
        "semantic_candidates_clean"
    ]
].head(20)

,target_clean,num_semantic_candidates_context,num_semantic_candidates_clean,semantic_candidates_clean
0,announced,20,20,"[agreed, planned, decided, expected, unveiled,..."
1,interested,3,3,"[involved, keen, realized]"
2,however,6,3,"[therefore, moreover, instead]"
3,thick,25,22,"[tall, dark, yellow, dry, shiny, rough, gray, ..."
4,remind,41,41,"[tell, ask, forget, wish, inform, remember, im..."
5,observing,57,52,"[monitoring, conducting, analyzing, photograph..."
6,told,30,27,"[quoted, insisted, spoke, informed, explained,..."
7,formed,27,26,"[merged, established, joined, created, founded..."
8,introduced,27,27,"[adopted, created, modified, used, changed, pr..."
9,attracted,17,15,"[garnered, encouraged, generated, grew, grown,..."
10,out,10,4,"[over, on, from, around]"
11,talk,27,26,"[tell, want, call, listen, know, come, hear, g..."
12,discovered,37,29,"[unearthed, believed, uncovered, excavated, tr..."
13,reason,10,9,"[question, thing, idea, sort, instance, explan..."
14,recognised,34,31,"[regarded, established, respected, accepted, c..."
15,imagine,23,20,"[remember, forget, know, tell, feel, understan..."
16,tour,35,35,"[event, tournament, trip, weekend, track, stag..."
17,trouble,12,8,"[lot, chance, things, possibility, weeks, reas..."
18,managed,23,23,"[helped, failed, struggled, allowed, worked, t..."
19,afford,49,48,"[pay, want, need, lose, spend, make, expect, g..."

In [40]:
# =========================
# БЛОК 5. Диагностика
# =========================

for _, row in df.head(12).iterrows():
    print("=" * 100)
    print("target:", row["target_clean"])
    print("после контекста:", row["semantic_candidates_context"][:15])
    print("после фильтра эквивалентов:", row["semantic_candidates_clean"][:15])
    print("удалено:", row["removed_by_near_equivalent_filter"][:8])

====================================================================================================
target: announced
после контекста: ['agreed', 'planned', 'decided', 'expected', 'unveiled', 'proposed', 'confirmed', 'approved', 'promised', 'scheduled', 'signed', 'rejected', 'issued', 'launched', 'offered']
после фильтра эквивалентов: ['agreed', 'planned', 'decided', 'expected', 'unveiled', 'proposed', 'confirmed', 'approved', 'promised', 'scheduled', 'signed', 'rejected', 'issued', 'launched', 'offered']
удалено: []
====================================================================================================
target: interested
после контекста: ['involved', 'keen', 'realized']
после фильтра эквивалентов: ['involved', 'keen', 'realized']
удалено: []
====================================================================================================
target: however
после контекста: ['although', 'though', 'nevertheless', 'therefore', 'moreover', 'instead']
после фильтра эквивалентов: ['therefore', 'moreover', 'instead']
удалено: [{'candidate': 'although', 'reason': 'too_high_vector_similarity', 'similarity': 0.9658}, {'candidate': 'though', 'reason': 'too_high_vector_similarity', 'similarity': 0.9302}, {'candidate': 'nevertheless', 'reason': 'wordnet_synonym', 'similarity': 0.8506}]
====================================================================================================
target: thick
после контекста: ['dense', 'thin', 'tall', 'dark', 'yellow', 'dry', 'shiny', 'deep', 'rough', 'gray', 'large', 'sturdy', 'shallow', 'soft', 'heavy']
после фильтра эквивалентов: ['tall', 'dark', 'yellow', 'dry', 'shiny', 'rough', 'gray', 'large', 'sturdy', 'shallow', 'soft', 'heavy', 'black', 'loose', 'flat']
удалено: [{'candidate': 'dense', 'reason': 'wordnet_synonym', 'similarity': 0.7718}, {'candidate': 'thin', 'reason': 'wordnet_antonym', 'similarity': 0.7357}, {'candidate': 'deep', 'reason': 'wordnet_synonym', 'similarity': 0.5771}]
====================================================================================================
target: remind
после контекста: ['tell', 'ask', 'forget', 'wish', 'inform', 'remember', 'impress', 'let', 'educate', 'motivate', 'understand', 'thank', 'want', 'listen', 'imagine']
после фильтра эквивалентов: ['tell', 'ask', 'forget', 'wish', 'inform', 'remember', 'impress', 'let', 'educate', 'motivate', 'understand', 'thank', 'want', 'listen', 'imagine']
удалено: []
====================================================================================================
target: observing
после контекста: ['monitoring', 'conducting', 'analyzing', 'photographing', 'keeping', 'witnessing', 'guiding', 'tracking', 'watching', 'studying', 'surveying', 'simulating', 'evaluating', 'setting', 'analysing']
после фильтра эквивалентов: ['monitoring', 'conducting', 'analyzing', 'photographing', 'witnessing', 'guiding', 'tracking', 'studying', 'surveying', 'simulating', 'evaluating', 'setting', 'analysing', 'assessing', 'interacting']
удалено: [{'candidate': 'keeping', 'reason': 'same_wordnet_synset', 'similarity': 0.5208}, {'candidate': 'watching', 'reason': 'same_wordnet_synset', 'similarity': 0.5058}, {'candidate': 'respecting', 'reason': 'same_wordnet_synset', 'similarity': 0.4797}, {'candidate': 'maintaining', 'reason': 'same_wordnet_synset', 'similarity': 0.4702}, {'candidate': 'detecting', 'reason': 'same_wordnet_synset', 'similarity': 0.4279}]
====================================================================================================
target: told
после контекста: ['asked', 'said', 'quoted', 'insisted', 'spoke', 'informed', 'explained', 'met', 'acknowledged', 'warned', 'suggested', 'wanted', 'talked', 'noted', 'added']
после фильтра эквивалентов: ['quoted', 'insisted', 'spoke', 'informed', 'explained', 'met', 'acknowledged', 'warned', 'suggested', 'wanted', 'talked', 'noted', 'added', 'stressed', 'contacted']
удалено: [{'candidate': 'asked', 'reason': 'too_high_vector_similarity', 'similarity': 0.8531}, {'candidate': 'said', 'reason': 'same_wordnet_synset', 'similarity': 0.8487}, {'candidate': 'assured', 'reason': 'same_wordnet_synset', 'similarity': 0.6278}]
====================================================================================================
target: formed
после контекста: ['merged', 'established', 'joined', 'created', 'founded', 'incorporated', 'became', 'called', 'known', 'composed', 'renamed', 'began', 'led', 'disbanded', 'organized']
после фильтра эквивалентов: ['merged', 'established', 'joined', 'created', 'founded', 'incorporated', 'became', 'called', 'known', 'composed', 'renamed', 'began', 'led', 'disbanded', 'dissolved']
удалено: [{'candidate': 'organized', 'reason': 'same_wordnet_synset', 'similarity': 0.582}]
====================================================================================================
target: introduced
после контекста: ['adopted', 'created', 'modified', 'used', 'changed', 'proposed', 'designed', 'replaced', 'called', 'expanded', 'included', 'passed', 'became', 'implemented', 'incorporated']
после фильтра эквивалентов: ['adopted', 'created', 'modified', 'used', 'changed', 'proposed', 'designed', 'replaced', 'called', 'expanded', 'included', 'passed', 'became', 'implemented', 'incorporated']
удалено: []
====================================================================================================
target: attracted
после контекста: ['drew', 'garnered', 'encouraged', 'generated', 'grew', 'grown', 'spurred', 'devoted', 'brought', 'enjoyed', 'drawn', 'aroused', 'seen', 'impressed', 'received']
после фильтра эквивалентов: ['garnered', 'encouraged', 'generated', 'grew', 'grown', 'spurred', 'devoted', 'brought', 'enjoyed', 'aroused', 'seen', 'impressed', 'received', 'viewed', 'offered']
удалено: [{'candidate': 'drew', 'reason': 'same_wordnet_synset', 'similarity': 0.6407}, {'candidate': 'drawn', 'reason': 'same_wordnet_synset', 'similarity': 0.5609}]
====================================================================================================
target: out
после контекста: ['up', 'off', 'back', 'away', 'into', 'down', 'over', 'on', 'from', 'around']
после фильтра эквивалентов: ['over', 'on', 'from', 'around']
удалено: [{'candidate': 'up', 'reason': 'too_high_vector_similarity', 'similarity': 0.8888}, {'candidate': 'off', 'reason': 'too_high_vector_similarity', 'similarity': 0.8723}, {'candidate': 'back', 'reason': 'too_high_vector_similarity', 'similarity': 0.8683}, {'candidate': 'away', 'reason': 'too_high_vector_similarity', 'similarity': 0.8584}, {'candidate': 'into', 'reason': 'too_high_vector_similarity', 'similarity': 0.8489}, {'candidate': 'down', 'reason': 'too_high_vector_similarity', 'similarity': 0.8282}]
====================================================================================================
target: talk
после контекста: ['tell', 'want', 'call', 'listen', 'know', 'come', 'hear', 'go', 'let', 'get', 'ask', 'answer', 'see', 'show', 'mind']
после фильтра эквивалентов: ['tell', 'want', 'call', 'listen', 'know', 'come', 'hear', 'go', 'let', 'get', 'ask', 'answer', 'see', 'show', 'mind']
удалено: [{'candidate': 'speak', 'reason': 'wordnet_synonym', 'similarity': 0.6819}]

In [41]:
# =========================
# БЛОК 5.1. Исправляем фильтр для служебных слов
# =========================

def near_equivalent_reason(candidate: str, row) -> Optional[str]:
    """
    Возвращает причину удаления кандидата,
    если он слишком близок к target.

    Важно:
    для discourse markers, предлогов и частиц НЕ используем
    фильтр высокой векторной близости, потому что для них
    близость как раз ожидаема:
    however -> therefore / moreover
    out -> up / off / away
    """
    candidate = clean_text(candidate).lower()
    target = row["target_clean"]
    target_pos = row["target_pos"]
    target_group = row["target_form_group"]

    similarity = vector_similarity(
        target,
        candidate,
        glove_model
    )

    # Для служебных слов не применяем high similarity как причину удаления.
    skip_high_similarity_filter = target_group in {
        "discourse_marker",
        "preposition_or_particle"
    }

    # Прямой синоним WordNet
    if candidate in get_wordnet_synonyms(target, target_pos):
        return "wordnet_synonym"

    # То же значение в WordNet
    if share_wordnet_synset(candidate, target, target_pos):
        return "same_wordnet_synset"

    # Антоним
    if is_antonym_candidate(candidate, target, target_pos):
        return "wordnet_antonym"

    # Противоположная эмоциональная полярность
    if has_opposite_emotion_polarity(candidate, target):
        return "opposite_emotion_polarity"

    # Слишком высокая векторная близость
    if (
        not skip_high_similarity_filter
        and similarity > MAX_ALLOWED_VECTOR_SIMILARITY
    ):
        return "too_high_vector_similarity"

    return None


df["semantic_candidates_clean"] = df.apply(
    apply_near_equivalent_filter,
    axis=1
)

df["removed_by_near_equivalent_filter"] = df.apply(
    collect_removed_by_near_equivalent_filter,
    axis=1
)

df["num_semantic_candidates_clean"] = df["semantic_candidates_clean"].apply(len)

df.loc[
    df["target_clean"].isin(["however", "out"]),
    [
        "target_clean",
        "semantic_candidates_context",
        "semantic_candidates_clean",
        "removed_by_near_equivalent_filter"
    ]
]

,target_clean,semantic_candidates_context,semantic_candidates_clean,removed_by_near_equivalent_filter
2,however,"[although, though, nevertheless, therefore, mo...","[although, though, therefore, moreover, instead]","[{'candidate': 'nevertheless', 'reason': 'word..."
10,out,"[up, off, back, away, into, down, over, on, fr...","[up, off, back, away, into, down, over, on, fr...",[]
66,however,"[although, nevertheless, therefore, moreover, ...","[although, therefore, moreover, instead]","[{'candidate': 'nevertheless', 'reason': 'word..."
104,however,"[although, though, nevertheless, therefore, mo...","[although, though, therefore, moreover, instead]","[{'candidate': 'nevertheless', 'reason': 'word..."
128,however,"[although, though, nevertheless, therefore, mo...","[although, though, therefore, moreover, instead]","[{'candidate': 'nevertheless', 'reason': 'word..."
198,out,"[off, away, down, over]","[off, away, down, over]",[]
203,however,"[although, nevertheless, therefore, moreover, ...","[although, therefore, moreover, instead]","[{'candidate': 'nevertheless', 'reason': 'word..."
232,out,"[up, off, back, down, from, around]","[up, off, back, down, from, around]",[]
278,however,"[although, though, nevertheless, therefore, mo...","[although, though, therefore, moreover, instead]","[{'candidate': 'nevertheless', 'reason': 'word..."
331,however,"[though, nevertheless, therefore, moreover, in...","[though, therefore, moreover, instead]","[{'candidate': 'nevertheless', 'reason': 'word..."

In [42]:
# =========================
# БЛОК 6. Learner corpus из answer_key
# =========================

def build_learner_errors_from_answer_key(answer_key_df: pd.DataFrame) -> pd.DataFrame:
    """
    Создает learner corpus из реальных дистракторов ЕГЭ.

    Каждая строка превращается в пары:
    target -> distractor_1
    target -> distractor_2
    target -> distractor_3
    """
    rows = []

    for _, row in answer_key_df.iterrows():
        target = clean_text(row.get("target", "")).lower()

        item_key = make_item_key(
            row.get("kod", ""),
            row.get("title", ""),
            row.get("task_id", "")
        )

        for col in [
            "distractor_1",
            "distractor_2",
            "distractor_3"
        ]:
            error_variant = clean_text(row.get(col, "")).lower()

            if not target or not error_variant:
                continue

            if error_variant == target:
                continue

            rows.append(
                {
                    "target": target,
                    "error_variant": error_variant,
                    "item_key": item_key,
                    "source": "EGE_answer_key",
                    "error_type": "real_ege_distractor",
                    "learner_sentence": "",
                    "correct_sentence": "",
                    "comment": "Реальный дистрактор из задания ЕГЭ"
                }
            )

    return pd.DataFrame(rows)

In [43]:
# =========================
# БЛОК 6. Learner corpus из REALEC
# =========================

def build_learner_errors_from_realec(realec_df: pd.DataFrame) -> pd.DataFrame:
    """
    Приводит REALEC к единому формату.

    Используем не только:
    correct_element -> error_variant

    но и контекст:
    learner_sentence
    correct_sentence
    comment
    error_type
    """
    rows = []

    for _, row in realec_df.iterrows():
        target = clean_text(row.get("correct_element", "")).lower()

        if not target:
            target = clean_text(row.get("target_head", "")).lower()

        error_variant = clean_text(row.get("error_variant", "")).lower()

        if not target or not error_variant:
            continue

        if target == error_variant:
            continue

        rows.append(
            {
                "target": target,
                "error_variant": error_variant,
                "item_key": "REALEC",
                "source": clean_text(row.get("source_error", "REALEC")) or "REALEC",
                "error_type": clean_text(row.get("error_type", "learner_error")),
                "learner_sentence": clean_text(row.get("learner_sentence", "")),
                "correct_sentence": clean_text(row.get("correct_sentence", "")),
                "comment": clean_text(row.get("comment", ""))
            }
        )

    return pd.DataFrame(rows)

In [44]:
# =========================
# БЛОК 6. Собираем общий learner corpus
# =========================

ege_learner_errors_df = build_learner_errors_from_answer_key(answer_key_df)
realec_learner_errors_df = build_learner_errors_from_realec(realec_df)

learner_errors_df = pd.concat(
    [
        ege_learner_errors_df,
        realec_learner_errors_df
    ],
    ignore_index=True
).drop_duplicates(
    subset=[
        "target",
        "error_variant",
        "item_key",
        "source"
    ]
).reset_index(drop=True)

print("EGE learner errors:", ege_learner_errors_df.shape)
print("REALEC learner errors:", realec_learner_errors_df.shape)
print("Общий learner_errors_df:", learner_errors_df.shape)

print("\nИсточники:")
print(learner_errors_df["source"].value_counts())

learner_errors_df.head()

EGE learner errors: (1027, 8)
REALEC learner errors: (339, 8)
Общий learner_errors_df: (1131, 8)

Источники:
source
EGE_answer_key    1027
REALEC             104
Name: count, dtype: int64

,target,error_variant,item_key,source,error_type,learner_sentence,correct_sentence,comment
0,announced,promoted,09B13D|Going on a hike|30,EGE_answer_key,real_ege_distractor,,,Реальный дистрактор из задания ЕГЭ
1,announced,extended,09B13D|Going on a hike|30,EGE_answer_key,real_ege_distractor,,,Реальный дистрактор из задания ЕГЭ
2,announced,presented,09B13D|Going on a hike|30,EGE_answer_key,real_ege_distractor,,,Реальный дистрактор из задания ЕГЭ
3,interested,delighted,09B13D|Going on a hike|31,EGE_answer_key,real_ege_distractor,,,Реальный дистрактор из задания ЕГЭ
4,interested,inspired,09B13D|Going on a hike|31,EGE_answer_key,real_ege_distractor,,,Реальный дистрактор из задания ЕГЭ

In [45]:
# =========================
# БЛОК 6. Контекст learner errors
# =========================

def build_learner_context(row) -> str:
    """
    Собирает текстовый контекст ошибки из learner corpus.
    """
    parts = [
        row.get("learner_sentence", ""),
        row.get("correct_sentence", ""),
        row.get("comment", ""),
        row.get("error_type", "")
    ]

    return clean_text(
        " ".join(
            clean_text(part)
            for part in parts
            if clean_text(part)
        )
    )


def get_contextual_learner_candidates(
    target: str,
    current_item_key: str,
    current_sentence: str,
    current_text: str,
    learner_errors_df: pd.DataFrame,
    topn: int = 20
) -> List[str]:
    """
    Возвращает learner candidates с учетом контекста.

    Для EGE answer_key контекста почти нет, поэтому они просто идут как пары.
    Для REALEC считаем похожесть текущего контекста на learner_sentence / correct_sentence.
    """
    target = clean_text(target).lower()

    matched = learner_errors_df[
        (learner_errors_df["target"].astype(str).str.lower().str.strip() == target)
        &
        (learner_errors_df["item_key"].astype(str) != str(current_item_key))
    ].copy()

    if matched.empty:
        return []

    matched["learner_context"] = matched.apply(
        build_learner_context,
        axis=1
    )

    current_context = clean_text(
        current_sentence + " " + current_text
    )

    # Если контекста у matched нет, возвращаем пары target -> error_variant.
    if matched["learner_context"].eq("").all():
        return (
            matched["error_variant"]
            .dropna()
            .astype(str)
            .str.lower()
            .str.strip()
            .drop_duplicates()
            .head(topn)
            .tolist()
        )

    contexts = matched["learner_context"].fillna("").tolist()

    try:
        vectorizer = TfidfVectorizer(
            stop_words="english",
            ngram_range=(1, 2),
            min_df=1
        )

        matrix = vectorizer.fit_transform(
            [current_context] + contexts
        )

        scores = cosine_similarity(
            matrix[0],
            matrix[1:]
        ).ravel()

    except ValueError:
        scores = np.zeros(len(matched))

    matched["learner_context_score"] = scores

    matched = matched.sort_values(
        by=[
            "learner_context_score",
            "source"
        ],
        ascending=[
            False,
            True
        ]
    )

    return (
        matched["error_variant"]
        .dropna()
        .astype(str)
        .str.lower()
        .str.strip()
        .drop_duplicates()
        .head(topn)
        .tolist()
    )

In [46]:
# =========================
# БЛОК 6. Добавляем learner candidates к df
# =========================

df["learner_candidates_raw"] = df.apply(
    lambda row: get_contextual_learner_candidates(
        target=row["target_clean"],
        current_item_key=row["item_key"],
        current_sentence=row["sentence_clean"],
        current_text=row["text_clean"],
        learner_errors_df=learner_errors_df,
        topn=20
    ),
    axis=1
)

df[
    [
        "target_clean",
        "learner_candidates_raw"
    ]
].head(20)

   target_clean                             learner_candidates_raw
0     announced                    [extended, promoted, presented]
1    interested                                                 []
2       however  [despite, otherwise, likewise, although, moreo...
3         thick                                                 []
4        remind                 [revise, review, recall, remember]
5     observing                                                 []
6          told                              [talked, spoke, said]
7        formed                                                 []
8    introduced                    [proposed, announced, welcomed]
9     attracted                                                 []
10          out                            [about, over, down, up]
11         talk                                 [tell, speak, say]
12   discovered                     [detected, invented, explored]
13       reason                                                 []
14   recognised                                                 []
15      imagine                                                 []
16         tour                            [trip, travel, journey]
17      trouble                                                 []
18      managed  [achieved, succeeded, completed, fulfilled, ha...
19       afford                          [present, provide, allow]

In [47]:
# =========================
# БЛОК 6. Фильтрация learner candidates
# =========================

def filter_learner_candidates(row) -> List[str]:
    """
    Применяет к learner candidates уже созданные фильтры:
    - грамматика;
    - контекст;
    - почти-эквиваленты.
    """
    result = []

    for candidate in row["learner_candidates_raw"]:
        if not is_grammar_compatible(candidate, row):
            continue

        if context_filter_reason(candidate, row) is not None:
            continue

        if near_equivalent_reason(candidate, row) is not None:
            continue

        result.append(candidate)

    return unique_list(result)


df["learner_candidates_clean"] = df.apply(
    filter_learner_candidates,
    axis=1
)

df[
    [
        "target_clean",
        "semantic_candidates_clean",
        "learner_candidates_raw",
        "learner_candidates_clean"
    ]
].head(20)

,target_clean,semantic_candidates_clean,learner_candidates_raw,learner_candidates_clean
0,announced,"[agreed, planned, decided, expected, unveiled,...","[extended, promoted, presented]","[extended, promoted, presented]"
1,interested,"[involved, keen, realized]",[],[]
2,however,"[although, though, therefore, moreover, instead]","[despite, otherwise, likewise, although, moreo...","[otherwise, although, moreover, therefore]"
3,thick,"[tall, dark, yellow, dry, shiny, rough, gray, ...",[],[]
4,remind,"[tell, ask, forget, wish, inform, remember, im...","[revise, review, recall, remember]","[revise, review, recall, remember]"
5,observing,"[monitoring, conducting, analyzing, photograph...",[],[]
6,told,"[quoted, insisted, spoke, informed, explained,...","[talked, spoke, said]","[talked, spoke]"
7,formed,"[merged, established, joined, created, founded...",[],[]
8,introduced,"[adopted, created, modified, used, changed, pr...","[proposed, announced, welcomed]","[proposed, announced, welcomed]"
9,attracted,"[garnered, encouraged, generated, grew, grown,...",[],[]
10,out,"[up, off, back, away, into, down, over, on, fr...","[about, over, down, up]","[over, down, up]"
11,talk,"[tell, want, call, listen, know, come, hear, g...","[tell, speak, say]","[tell, say]"
12,discovered,"[unearthed, believed, uncovered, excavated, tr...","[detected, invented, explored]","[invented, explored]"
13,reason,"[question, thing, idea, sort, instance, explan...",[],[]
14,recognised,"[regarded, established, respected, accepted, c...",[],[]
15,imagine,"[remember, forget, know, tell, feel, understan...",[],[]
16,tour,"[event, tournament, trip, weekend, track, stag...","[trip, travel, journey]","[trip, travel, journey]"
17,trouble,"[lot, chance, things, possibility, weeks, reas...",[],[]
18,managed,"[helped, failed, struggled, allowed, worked, t...","[achieved, succeeded, completed, fulfilled, ha...","[achieved, succeeded, completed, fulfilled, ma..."
19,afford,"[pay, want, need, lose, spend, make, expect, g...","[present, provide, allow]","[provide, allow]"

In [48]:
df[
    [
        "target_clean",
        "semantic_candidates_clean",
        "learner_candidates_raw",
        "learner_candidates_clean"
    ]
].head(20)

,target_clean,semantic_candidates_clean,learner_candidates_raw,learner_candidates_clean
0,announced,"[agreed, planned, decided, expected, unveiled,...","[extended, promoted, presented]","[extended, promoted, presented]"
1,interested,"[involved, keen, realized]",[],[]
2,however,"[although, though, therefore, moreover, instead]","[despite, otherwise, likewise, although, moreo...","[otherwise, although, moreover, therefore]"
3,thick,"[tall, dark, yellow, dry, shiny, rough, gray, ...",[],[]
4,remind,"[tell, ask, forget, wish, inform, remember, im...","[revise, review, recall, remember]","[revise, review, recall, remember]"
5,observing,"[monitoring, conducting, analyzing, photograph...",[],[]
6,told,"[quoted, insisted, spoke, informed, explained,...","[talked, spoke, said]","[talked, spoke]"
7,formed,"[merged, established, joined, created, founded...",[],[]
8,introduced,"[adopted, created, modified, used, changed, pr...","[proposed, announced, welcomed]","[proposed, announced, welcomed]"
9,attracted,"[garnered, encouraged, generated, grew, grown,...",[],[]
10,out,"[up, off, back, away, into, down, over, on, fr...","[about, over, down, up]","[over, down, up]"
11,talk,"[tell, want, call, listen, know, come, hear, g...","[tell, speak, say]","[tell, say]"
12,discovered,"[unearthed, believed, uncovered, excavated, tr...","[detected, invented, explored]","[invented, explored]"
13,reason,"[question, thing, idea, sort, instance, explan...",[],[]
14,recognised,"[regarded, established, respected, accepted, c...",[],[]
15,imagine,"[remember, forget, know, tell, feel, understan...",[],[]
16,tour,"[event, tournament, trip, weekend, track, stag...","[trip, travel, journey]","[trip, travel, journey]"
17,trouble,"[lot, chance, things, possibility, weeks, reas...",[],[]
18,managed,"[helped, failed, struggled, allowed, worked, t...","[achieved, succeeded, completed, fulfilled, ha...","[achieved, succeeded, completed, fulfilled, ma..."
19,afford,"[pay, want, need, lose, spend, make, expect, g...","[present, provide, allow]","[provide, allow]"

In [49]:
# =========================
# БЛОК 7. Настройки ранжирования
# =========================

# Если True, используем реальные дистракторы текущего задания.
# Это полезно для демонстрации качества на размеченном корпусе.
# Если нужна честная проверка генерации без подсказки, поставь False.
USE_CURRENT_GOLD_EGE_DISTRACTORS = False

# Бонусы за источник кандидата
SOURCE_BONUSES = {
    "SemanticModel": 0.05,
    "LearnerCorpus": 0.25,
    "CurrentGoldEGE": 0.45
}

# Слишком высокая близость опасна только для чисто семантических кандидатов.
# Для learner / gold кандидатов это не штрафуем.
HIGH_SIMILARITY_PENALTY = 0.15
HIGH_SIMILARITY_THRESHOLD = 0.78

In [50]:
# =========================
# БЛОК 7. Объединяем кандидатов с источниками
# =========================

def add_candidate_to_pool(pool: Dict[str, Dict], candidate: str, source: str):
    """
    Добавляет кандидата в общий пул.

    Если кандидат уже есть, просто добавляет новый источник.
    """
    candidate = clean_text(candidate).lower()

    if not candidate:
        return

    if candidate not in pool:
        pool[candidate] = {
            "candidate": candidate,
            "sources": []
        }

    if source not in pool[candidate]["sources"]:
        pool[candidate]["sources"].append(source)


def build_candidate_pool(row) -> List[Dict]:
    """
    Собирает кандидатов из всех источников:
    - semantic_candidates_clean
    - learner_candidates_clean
    - gold_distractors, если включен режим USE_CURRENT_GOLD_EGE_DISTRACTORS
    """
    pool = {}

    for candidate in row["semantic_candidates_clean"]:
        add_candidate_to_pool(
            pool,
            candidate,
            "SemanticModel"
        )

    for candidate in row["learner_candidates_clean"]:
        add_candidate_to_pool(
            pool,
            candidate,
            "LearnerCorpus"
        )

    if USE_CURRENT_GOLD_EGE_DISTRACTORS:
        for candidate in row["gold_distractors"]:
            add_candidate_to_pool(
                pool,
                candidate,
                "CurrentGoldEGE"
            )

    return list(pool.values())

In [51]:
# =========================
# БЛОК 7. Скоринг кандидата
# =========================

def score_candidate(candidate_record: Dict, row) -> Dict:
    """
    Считает итоговый score кандидата.

    Компоненты:
    - GloVe similarity к target;
    - бонус за источник;
    - штраф за слишком высокую близость, если кандидат только из SemanticModel.
    """
    candidate = candidate_record["candidate"]
    sources = candidate_record["sources"]
    target = row["target_clean"]
    target_group = row["target_form_group"]

    similarity = vector_similarity(
        target,
        candidate,
        glove_model
    )

    source_bonus = sum(
        SOURCE_BONUSES.get(source, 0.0)
        for source in sources
    )

    penalty = 0.0

    protected_sources = {
        "LearnerCorpus",
        "CurrentGoldEGE"
    }

    is_protected = bool(
        set(sources) & protected_sources
    )

    # Для discourse markers и particles высокая близость допустима.
    is_function_word_group = target_group in {
        "discourse_marker",
        "preposition_or_particle"
    }

    if (
        not is_protected
        and not is_function_word_group
        and similarity > HIGH_SIMILARITY_THRESHOLD
    ):
        penalty = HIGH_SIMILARITY_PENALTY

    final_score = similarity + source_bonus - penalty

    return {
        "candidate": candidate,
        "sources": sources,
        "similarity": similarity,
        "source_bonus": source_bonus,
        "penalty": penalty,
        "final_score": final_score
    }

In [52]:
# =========================
# БЛОК 7. Ранжирование кандидатов
# =========================

def rank_candidates_for_row(row) -> List[Dict]:
    """
    Собирает и ранжирует кандидатов для одной строки.
    """
    pool = build_candidate_pool(row)

    scored = [
        score_candidate(candidate_record, row)
        for candidate_record in pool
    ]

    scored = sorted(
        scored,
        key=lambda x: x["final_score"],
        reverse=True
    )

    return scored


df["ranked_candidates"] = df.apply(
    rank_candidates_for_row,
    axis=1
)

df["ranked_candidate_words"] = df["ranked_candidates"].apply(
    lambda ranked: [
        item["candidate"]
        for item in ranked
    ]
)

df[
    [
        "target_clean",
        "semantic_candidates_clean",
        "learner_candidates_clean",
        "gold_distractors",
        "ranked_candidate_words"
    ]
].head(20)

,target_clean,semantic_candidates_clean,learner_candidates_clean,gold_distractors,ranked_candidate_words
0,announced,"[agreed, planned, decided, expected, unveiled,...","[extended, promoted, presented]","[promoted, extended, presented]","[presented, agreed, planned, decided, extended..."
1,interested,"[involved, keen, realized]",[],"[delighted, inspired, excited]","[involved, keen, realized]"
2,however,"[although, though, therefore, moreover, instead]","[otherwise, although, moreover, therefore]","[moreover, although, otherwise]","[although, therefore, moreover, though, otherw..."
3,thick,"[tall, dark, yellow, dry, shiny, rough, gray, ...",[],"[heavy, strong, rich]","[tall, dark, yellow, dry, shiny, rough, gray, ..."
4,remind,"[tell, ask, forget, wish, inform, remember, im...","[revise, review, recall, remember]","[review, remember, reflect]","[remember, tell, ask, forget, wish, inform, im..."
5,observing,"[monitoring, conducting, analyzing, photograph...",[],"[obtaining, offending, objecting]","[monitoring, conducting, analyzing, photograph..."
6,told,"[quoted, insisted, spoke, informed, explained,...","[talked, spoke]","[talked, spoke, said]","[spoke, talked, quoted, insisted, informed, ex..."
7,formed,"[merged, established, joined, created, founded...",[],"[kept, held, used]","[merged, established, joined, created, founded..."
8,introduced,"[adopted, created, modified, used, changed, pr...","[proposed, announced, welcomed]","[called, greeted, met]","[proposed, announced, adopted, created, modifi..."
9,attracted,"[garnered, encouraged, generated, grew, grown,...",[],"[involved, appealed, engaged]","[garnered, encouraged, generated, grew, grown,..."
10,out,"[up, off, back, away, into, down, over, on, fr...","[over, down, up]","[up, down, on]","[up, down, over, off, back, away, into, on, fr..."
11,talk,"[tell, want, call, listen, know, come, hear, g...","[tell, say]","[tell, discuss, say]","[tell, say, want, call, listen, know, come, he..."
12,discovered,"[unearthed, believed, uncovered, excavated, tr...","[invented, explored]","[determined, revealed, disclosed]","[unearthed, believed, invented, uncovered, exp..."
13,reason,"[question, thing, idea, sort, instance, explan...",[],"[matter, account, cause]","[thing, idea, sort, instance, explanation, pos..."
14,recognised,"[regarded, established, respected, accepted, c...",[],"[resembled, received, reviewed]","[regarded, established, respected, accepted, c..."
15,imagine,"[remember, forget, know, tell, feel, understan...",[],"[visualise, invent, expect]","[feel, understand, realize, happen, mind, want..."
16,tour,"[event, tournament, trip, weekend, track, stag...","[trip, travel, journey]","[travel, voyage, journey]","[trip, journey, travel, event, tournament, wee..."
17,trouble,"[lot, chance, things, possibility, weeks, reas...",[],"[problem, fault, worry]","[lot, chance, things, possibility, weeks, reas..."
18,managed,"[helped, failed, struggled, allowed, worked, t...","[achieved, succeeded, completed, fulfilled, ma...","[succeeded, fulfilled, completed]","[maintained, helped, completed, failed, strugg..."
19,afford,"[pay, want, need, lose, spend, make, expect, g...","[provide, allow]","[approve, arrange, allow]","[provide, allow, pay, want, need, lose, spend,..."

In [53]:
# =========================
# БЛОК 7. Диагностика ранжирования
# =========================

for _, row in df.head(12).iterrows():
    print("=" * 100)
    print("target:", row["target_clean"])
    print("gold:", row["gold_distractors"])
    print("semantic:", row["semantic_candidates_clean"][:8])
    print("learner:", row["learner_candidates_clean"][:8])
    print("ranked top-10:")

    for item in row["ranked_candidates"][:10]:
        print(
            item["candidate"],
            "| score:",
            round(item["final_score"], 4),
            "| sim:",
            round(item["similarity"], 4),
            "| sources:",
            item["sources"]
        )

====================================================================================================
target: announced
gold: ['promoted', 'extended', 'presented']
semantic: ['agreed', 'planned', 'decided', 'expected', 'unveiled', 'proposed', 'confirmed', 'approved']
learner: ['extended', 'promoted', 'presented']
ranked top-10:
presented | score: 0.8601 | sim: 0.6101 | sources: ['LearnerCorpus']
agreed | score: 0.8209 | sim: 0.7709 | sources: ['SemanticModel']
planned | score: 0.7989 | sim: 0.7489 | sources: ['SemanticModel']
decided | score: 0.7955 | sim: 0.7455 | sources: ['SemanticModel']
extended | score: 0.7869 | sim: 0.5369 | sources: ['LearnerCorpus']
expected | score: 0.783 | sim: 0.733 | sources: ['SemanticModel']
unveiled | score: 0.7611 | sim: 0.7111 | sources: ['SemanticModel']
proposed | score: 0.7497 | sim: 0.6997 | sources: ['SemanticModel']
confirmed | score: 0.7478 | sim: 0.6978 | sources: ['SemanticModel']
approved | score: 0.7446 | sim: 0.6946 | sources: ['SemanticModel']
====================================================================================================
target: interested
gold: ['delighted', 'inspired', 'excited']
semantic: ['involved', 'keen', 'realized']
learner: []
ranked top-10:
involved | score: 0.739 | sim: 0.689 | sources: ['SemanticModel']
keen | score: 0.662 | sim: 0.612 | sources: ['SemanticModel']
realized | score: 0.6538 | sim: 0.6038 | sources: ['SemanticModel']
====================================================================================================
target: however
gold: ['moreover', 'although', 'otherwise']
semantic: ['although', 'though', 'therefore', 'moreover', 'instead']
learner: ['otherwise', 'although', 'moreover', 'therefore']
ranked top-10:
although | score: 1.2658 | sim: 0.9658 | sources: ['SemanticModel', 'LearnerCorpus']
therefore | score: 1.0824 | sim: 0.7824 | sources: ['SemanticModel', 'LearnerCorpus']
moreover | score: 1.0694 | sim: 0.7694 | sources: ['SemanticModel', 'LearnerCorpus']
though | score: 0.9802 | sim: 0.9302 | sources: ['SemanticModel']
otherwise | score: 0.9492 | sim: 0.6992 | sources: ['LearnerCorpus']
instead | score: 0.8017 | sim: 0.7517 | sources: ['SemanticModel']
====================================================================================================
target: thick
gold: ['heavy', 'strong', 'rich']
semantic: ['tall', 'dark', 'yellow', 'dry', 'shiny', 'rough', 'gray', 'large']
learner: []
ranked top-10:
tall | score: 0.7283 | sim: 0.6783 | sources: ['SemanticModel']
dark | score: 0.7154 | sim: 0.6654 | sources: ['SemanticModel']
yellow | score: 0.6688 | sim: 0.6188 | sources: ['SemanticModel']
dry | score: 0.6441 | sim: 0.5941 | sources: ['SemanticModel']
shiny | score: 0.6343 | sim: 0.5843 | sources: ['SemanticModel']
rough | score: 0.627 | sim: 0.577 | sources: ['SemanticModel']
gray | score: 0.6214 | sim: 0.5714 | sources: ['SemanticModel']
large | score: 0.6214 | sim: 0.5714 | sources: ['SemanticModel']
sturdy | score: 0.6179 | sim: 0.5679 | sources: ['SemanticModel']
shallow | score: 0.6166 | sim: 0.5666 | sources: ['SemanticModel']
====================================================================================================
target: remind
gold: ['review', 'remember', 'reflect']
semantic: ['tell', 'ask', 'forget', 'wish', 'inform', 'remember', 'impress', 'let']
learner: ['revise', 'review', 'recall', 'remember']
ranked top-10:
remember | score: 0.9686 | sim: 0.6686 | sources: ['SemanticModel', 'LearnerCorpus']
tell | score: 0.8075 | sim: 0.7575 | sources: ['SemanticModel']
ask | score: 0.7271 | sim: 0.6771 | sources: ['SemanticModel']
forget | score: 0.7242 | sim: 0.6742 | sources: ['SemanticModel']
wish | score: 0.7215 | sim: 0.6715 | sources: ['SemanticModel']
inform | score: 0.7188 | sim: 0.6688 | sources: ['SemanticModel']
impress | score: 0.7152 | sim: 0.6652 | sources: ['SemanticModel']
let | score: 0.6995 | sim: 0.6495 | sources: ['SemanticModel']
educate | score: 0.6993 | sim: 0.6493 | sources: ['SemanticModel']
motivate | score: 0.6986 | sim: 0.6486 | sources: ['SemanticModel']
====================================================================================================
target: observing
gold: ['obtaining', 'offending', 'objecting']
semantic: ['monitoring', 'conducting', 'analyzing', 'photographing', 'witnessing', 'guiding', 'tracking', 'studying']
learner: []
ranked top-10:
monitoring | score: 0.6635 | sim: 0.6135 | sources: ['SemanticModel']
conducting | score: 0.6276 | sim: 0.5776 | sources: ['SemanticModel']
analyzing | score: 0.6042 | sim: 0.5542 | sources: ['SemanticModel']
photographing | score: 0.5732 | sim: 0.5232 | sources: ['SemanticModel']
witnessing | score: 0.5696 | sim: 0.5196 | sources: ['SemanticModel']
guiding | score: 0.5578 | sim: 0.5078 | sources: ['SemanticModel']
tracking | score: 0.5563 | sim: 0.5063 | sources: ['SemanticModel']
studying | score: 0.5546 | sim: 0.5046 | sources: ['SemanticModel']
surveying | score: 0.5478 | sim: 0.4978 | sources: ['SemanticModel']
simulating | score: 0.545 | sim: 0.495 | sources: ['SemanticModel']
====================================================================================================
target: told
gold: ['talked', 'spoke', 'said']
semantic: ['quoted', 'insisted', 'spoke', 'informed', 'explained', 'met', 'acknowledged', 'warned']
learner: ['talked', 'spoke']
ranked top-10:
spoke | score: 1.0432 | sim: 0.7432 | sources: ['SemanticModel', 'LearnerCorpus']
talked | score: 0.969 | sim: 0.669 | sources: ['SemanticModel', 'LearnerCorpus']
quoted | score: 0.8105 | sim: 0.7605 | sources: ['SemanticModel']
insisted | score: 0.8098 | sim: 0.7598 | sources: ['SemanticModel']
informed | score: 0.7786 | sim: 0.7286 | sources: ['SemanticModel']
explained | score: 0.7618 | sim: 0.7118 | sources: ['SemanticModel']
met | score: 0.7581 | sim: 0.7081 | sources: ['SemanticModel']
acknowledged | score: 0.7578 | sim: 0.7078 | sources: ['SemanticModel']
warned | score: 0.7507 | sim: 0.7007 | sources: ['SemanticModel']
suggested | score: 0.7334 | sim: 0.6834 | sources: ['SemanticModel']
====================================================================================================
target: formed
gold: ['kept', 'held', 'used']
semantic: ['merged', 'established', 'joined', 'created', 'founded', 'incorporated', 'became', 'called']
learner: []
ranked top-10:
merged | score: 0.7769 | sim: 0.7269 | sources: ['SemanticModel']
established | score: 0.7621 | sim: 0.7121 | sources: ['SemanticModel']
joined | score: 0.7618 | sim: 0.7118 | sources: ['SemanticModel']
created | score: 0.7543 | sim: 0.7043 | sources: ['SemanticModel']
founded | score: 0.7532 | sim: 0.7032 | sources: ['SemanticModel']
incorporated | score: 0.7418 | sim: 0.6918 | sources: ['SemanticModel']
became | score: 0.6954 | sim: 0.6454 | sources: ['SemanticModel']
called | score: 0.6766 | sim: 0.6266 | sources: ['SemanticModel']
known | score: 0.6711 | sim: 0.6211 | sources: ['SemanticModel']
composed | score: 0.6659 | sim: 0.6159 | sources: ['SemanticModel']
====================================================================================================
target: introduced
gold: ['called', 'greeted', 'met']
semantic: ['adopted', 'created', 'modified', 'used', 'changed', 'proposed', 'designed', 'replaced']
learner: ['proposed', 'announced', 'welcomed']
ranked top-10:
proposed | score: 0.9685 | sim: 0.6685 | sources: ['SemanticModel', 'LearnerCorpus']
announced | score: 0.8928 | sim: 0.5928 | sources: ['SemanticModel', 'LearnerCorpus']
adopted | score: 0.8018 | sim: 0.7518 | sources: ['SemanticModel']
created | score: 0.748 | sim: 0.698 | sources: ['SemanticModel']
modified | score: 0.7353 | sim: 0.6853 | sources: ['SemanticModel']
used | score: 0.7214 | sim: 0.6714 | sources: ['SemanticModel']
changed | score: 0.7199 | sim: 0.6699 | sources: ['SemanticModel']
designed | score: 0.7077 | sim: 0.6577 | sources: ['SemanticModel']
replaced | score: 0.7076 | sim: 0.6576 | sources: ['SemanticModel']
called | score: 0.7058 | sim: 0.6558 | sources: ['SemanticModel']
====================================================================================================
target: attracted
gold: ['involved', 'appealed', 'engaged']
semantic: ['garnered', 'encouraged', 'generated', 'grew', 'grown', 'spurred', 'devoted', 'brought']
learner: []
ranked top-10:
garnered | score: 0.6696 | sim: 0.6196 | sources: ['SemanticModel']
encouraged | score: 0.6546 | sim: 0.6046 | sources: ['SemanticModel']
generated | score: 0.6508 | sim: 0.6008 | sources: ['SemanticModel']
grew | score: 0.6395 | sim: 0.5895 | sources: ['SemanticModel']
grown | score: 0.6331 | sim: 0.5831 | sources: ['SemanticModel']
spurred | score: 0.6324 | sim: 0.5824 | sources: ['SemanticModel']
devoted | score: 0.6182 | sim: 0.5682 | sources: ['SemanticModel']
brought | score: 0.6153 | sim: 0.5653 | sources: ['SemanticModel']
enjoyed | score: 0.612 | sim: 0.562 | sources: ['SemanticModel']
aroused | score: 0.6058 | sim: 0.5558 | sources: ['SemanticModel']
====================================================================================================
target: out
gold: ['up', 'down', 'on']
semantic: ['up', 'off', 'back', 'away', 'into', 'down', 'over', 'on']
learner: ['over', 'down', 'up']
ranked top-10:
up | score: 1.1888 | sim: 0.8888 | sources: ['SemanticModel', 'LearnerCorpus']
down | score: 1.1282 | sim: 0.8282 | sources: ['SemanticModel', 'LearnerCorpus']
over | score: 1.1035 | sim: 0.8035 | sources: ['SemanticModel', 'LearnerCorpus']
off | score: 0.9223 | sim: 0.8723 | sources: ['SemanticModel']
back | score: 0.9183 | sim: 0.8683 | sources: ['SemanticModel']
away | score: 0.9084 | sim: 0.8584 | sources: ['SemanticModel']
into | score: 0.8989 | sim: 0.8489 | sources: ['SemanticModel']
on | score: 0.8199 | sim: 0.7699 | sources: ['SemanticModel']
from | score: 0.8173 | sim: 0.7673 | sources: ['SemanticModel']
around | score: 0.789 | sim: 0.739 | sources: ['SemanticModel']
====================================================================================================
target: talk
gold: ['tell', 'discuss', 'say']
semantic: ['tell', 'want', 'call', 'listen', 'know', 'come', 'hear', 'go']
learner: ['tell', 'say']
ranked top-10:
tell | score: 1.0678 | sim: 0.7678 | sources: ['SemanticModel', 'LearnerCorpus']
say | score: 0.9826 | sim: 0.6826 | sources: ['SemanticModel', 'LearnerCorpus']
want | score: 0.8067 | sim: 0.7567 | sources: ['SemanticModel']
call | score: 0.7963 | sim: 0.7463 | sources: ['SemanticModel']
listen | score: 0.7893 | sim: 0.7393 | sources: ['SemanticModel']
know | score: 0.7875 | sim: 0.7375 | sources: ['SemanticModel']
come | score: 0.7803 | sim: 0.7303 | sources: ['SemanticModel']
hear | score: 0.7691 | sim: 0.7191 | sources: ['SemanticModel']
go | score: 0.7654 | sim: 0.7154 | sources: ['SemanticModel']
let | score: 0.7625 | sim: 0.7125 | sources: ['SemanticModel']

In [54]:
# =========================
# БЛОК 8. Загрузка CEFR vocabulary profile
# =========================

CEFR_URL = "https://raw.githubusercontent.com/openlanguageprofiles/olp-en-cefrj/master/cefrj-vocabulary-profile-1.5.csv"

cefr_df = pd.read_csv(CEFR_URL)

print("CEFR dataframe:", cefr_df.shape)
print(cefr_df.columns.tolist())

cefr_df.head()

CEFR dataframe: (7799, 6)
['headword', 'pos', 'CEFR', 'CoreInventory 1', 'CoreInventory 2', 'Threshold']

          headword         pos CEFR CoreInventory 1 CoreInventory 2 Threshold
0                a  determiner   A1             NaN             NaN       NaN
1  a.m./A.M./am/AM      adverb   A1             NaN             NaN       NaN
2          abandon        verb   B1             NaN             NaN       NaN
3        abandoned   adjective   B2             NaN             NaN       NaN
4          ability        noun   A2             NaN             NaN       NaN

In [55]:
# =========================
# БЛОК 8. Создаем словарь word -> CEFR
# =========================

CEFR_ORDER = {
    "A1": 1,
    "A2": 2,
    "B1": 3,
    "B2": 4,
    "C1": 5,
    "C2": 6
}

# Ручные исправления для слов, которые CEFR-J может не распознать
CEFR_OVERRIDES = {
    "announced": "B1",
    "presented": "A1",
    "extended": "B1",
    "promoted": "B1",
    "inspired": "B1",
    "interested": "A1",
    "delighted": "B1",
    "excited": "A1",
    "however": "A2",
    "therefore": "B1",
    "moreover": "B1",
    "otherwise": "B1",
    "meanwhile": "B1"
}


def detect_cefr_columns(cefr_df: pd.DataFrame) -> Tuple[str, str]:
    """
    Автоматически определяет, где в таблице слово и где уровень CEFR.
    """
    possible_word_columns = [
        "headword",
        "word",
        "lemma",
        "entry"
    ]

    possible_level_columns = [
        "CEFR",
        "cefr",
        "level",
        "Level"
    ]

    word_column = None
    level_column = None

    for col in possible_word_columns:
        if col in cefr_df.columns:
            word_column = col
            break

    for col in possible_level_columns:
        if col in cefr_df.columns:
            level_column = col
            break

    if word_column is None:
        word_column = cefr_df.columns[0]

    if level_column is None:
        level_column = cefr_df.columns[-1]

    return word_column, level_column


word_column, level_column = detect_cefr_columns(cefr_df)

print("word_column:", word_column)
print("level_column:", level_column)


cefr_level_map = {}

for _, row in cefr_df.iterrows():
    word = clean_text(row[word_column]).lower()
    level = clean_text(row[level_column]).upper()[:2]

    if not word:
        continue

    if level not in CEFR_ORDER:
        continue

    # Если слово встречается несколько раз, берем самый простой уровень.
    if (
        word not in cefr_level_map
        or CEFR_ORDER[level] < CEFR_ORDER[cefr_level_map[word]]
    ):
        cefr_level_map[word] = level


cefr_level_map.update(CEFR_OVERRIDES)

print("Количество слов в CEFR map:", len(cefr_level_map))

word_column: headword
level_column: CEFR
Количество слов в CEFR map: 6868

In [56]:
# =========================
# БЛОК 8. Функция определения CEFR уровня
# =========================

def get_cefr_level(word: str) -> Optional[str]:
    """
    Возвращает CEFR-уровень слова.

    Если точная форма не найдена, пробуем:
    - лемму;
    - части словосочетания.
    """
    word = clean_text(word).lower()

    if not word:
        return None

    if word in cefr_level_map:
        return cefr_level_map[word]

    lemma = get_candidate_lemma(word)

    if lemma in cefr_level_map:
        return cefr_level_map[lemma]

    # Для словосочетаний берем максимальный уровень частей.
    part_levels = []

    for part in word.split():
        part = clean_text(part).lower()

        if part in cefr_level_map:
            part_levels.append(cefr_level_map[part])
            continue

        part_lemma = get_candidate_lemma(part)

        if part_lemma in cefr_level_map:
            part_levels.append(cefr_level_map[part_lemma])

    if part_levels:
        return max(
            part_levels,
            key=lambda level: CEFR_ORDER[level]
        )

    return None

In [57]:
# =========================
# БЛОК 8. Проверка CEFR совместимости
# =========================

MIN_CEFR_LEVEL = "A1"
MAX_CEFR_LEVEL = "B2"
KEEP_UNKNOWN_CEFR = True


def is_cefr_compatible(candidate: str, row) -> bool:
    """
    Проверяет, подходит ли кандидат по уровню CEFR.

    Логика:
    - выше B2 отсекаем;
    - unknown можно оставить, но отправить на диагностику;
    - если target известен, не берем кандидата намного сложнее target.
    """
    candidate_level = get_cefr_level(candidate)
    target_level = get_cefr_level(row["target_clean"])

    if candidate_level is None:
        return KEEP_UNKNOWN_CEFR

    candidate_rank = CEFR_ORDER[candidate_level]

    if candidate_rank < CEFR_ORDER[MIN_CEFR_LEVEL]:
        return False

    if candidate_rank > CEFR_ORDER[MAX_CEFR_LEVEL]:
        return False

    if target_level is not None:
        target_rank = CEFR_ORDER[target_level]

        # Кандидат не должен быть больше чем на 2 уровня сложнее target.
        if candidate_rank - target_rank > 2:
            return False

    return True

In [58]:
# =========================
# БЛОК 8. Применяем CEFR к ranked_candidates
# =========================

def apply_cefr_to_ranked_candidates(row) -> List[Dict]:
    """
    Фильтрует уже ранжированные кандидаты по CEFR.
    """
    result = []

    for item in row["ranked_candidates"]:
        candidate = item["candidate"]

        if is_cefr_compatible(candidate, row):
            new_item = item.copy()
            new_item["candidate_cefr"] = get_cefr_level(candidate)
            new_item["target_cefr"] = get_cefr_level(row["target_clean"])
            result.append(new_item)

    return result


df["ranked_candidates_cefr"] = df.apply(
    apply_cefr_to_ranked_candidates,
    axis=1
)

df["ranked_candidate_words_cefr"] = df["ranked_candidates_cefr"].apply(
    lambda ranked: [
        item["candidate"]
        for item in ranked
    ]
)

df[
    [
        "target_clean",
        "ranked_candidate_words",
        "ranked_candidate_words_cefr"
    ]
].head(20)

,target_clean,ranked_candidate_words,ranked_candidate_words_cefr
0,announced,"[presented, agreed, planned, decided, extended...","[presented, agreed, planned, decided, extended..."
1,interested,"[involved, keen, realized]","[involved, realized]"
2,however,"[although, therefore, moreover, though, otherw...","[although, therefore, moreover, though, otherw..."
3,thick,"[tall, dark, yellow, dry, shiny, rough, gray, ...","[tall, dark, yellow, dry, shiny, rough, gray, ..."
4,remind,"[remember, tell, ask, forget, wish, inform, im...","[remember, tell, ask, forget, wish, inform, im..."
5,observing,"[monitoring, conducting, analyzing, photograph...","[monitoring, conducting, analyzing, photograph..."
6,told,"[spoke, talked, quoted, insisted, informed, ex...","[spoke, talked, insisted, informed, explained,..."
7,formed,"[merged, established, joined, created, founded...","[established, joined, created, incorporated, b..."
8,introduced,"[proposed, announced, adopted, created, modifi...","[announced, created, modified, used, changed, ..."
9,attracted,"[garnered, encouraged, generated, grew, grown,...","[garnered, encouraged, generated, grew, grown,..."
10,out,"[up, down, over, off, back, away, into, on, fr...","[up, down, over, off, back, away, into, on, fr..."
11,talk,"[tell, say, want, call, listen, know, come, he...","[tell, say, want, call, listen, know, come, he..."
12,discovered,"[unearthed, believed, invented, uncovered, exp...","[unearthed, believed, invented, uncovered, exp..."
13,reason,"[thing, idea, sort, instance, explanation, pos...","[thing, idea, sort, instance, explanation, pos..."
14,recognised,"[regarded, established, respected, accepted, c...","[regarded, established, respected, accepted, c..."
15,imagine,"[feel, understand, realize, happen, mind, want...","[feel, understand, realize, happen, mind, want..."
16,tour,"[trip, journey, travel, event, tournament, wee...","[trip, journey, travel, event, tournament, wee..."
17,trouble,"[lot, chance, things, possibility, weeks, reas...","[lot, chance, things, possibility, weeks, reas..."
18,managed,"[maintained, helped, completed, failed, strugg...","[maintained, helped, completed, failed, strugg..."
19,afford,"[provide, allow, pay, want, need, lose, spend,...","[provide, allow, pay, want, need, lose, spend,..."

In [59]:
# =========================
# БЛОК 8. Диагностика CEFR
# =========================

for _, row in df.head(12).iterrows():
    print("=" * 100)
    print("target:", row["target_clean"])
    print("target_cefr:", get_cefr_level(row["target_clean"]))
    print("ranked after CEFR:")

    for item in row["ranked_candidates_cefr"][:10]:
        print(
            item["candidate"],
            "| cefr:",
            item["candidate_cefr"],
            "| score:",
            round(item["final_score"], 4),
            "| sources:",
            item["sources"]
        )

====================================================================================================
target: announced
target_cefr: B1
ranked after CEFR:
presented | cefr: A1 | score: 0.8601 | sources: ['LearnerCorpus']
agreed | cefr: A1 | score: 0.8209 | sources: ['SemanticModel']
planned | cefr: A1 | score: 0.7989 | sources: ['SemanticModel']
decided | cefr: A2 | score: 0.7955 | sources: ['SemanticModel']
extended | cefr: B1 | score: 0.7869 | sources: ['LearnerCorpus']
expected | cefr: B2 | score: 0.783 | sources: ['SemanticModel']
unveiled | cefr: None | score: 0.7611 | sources: ['SemanticModel']
proposed | cefr: B2 | score: 0.7497 | sources: ['SemanticModel']
confirmed | cefr: B1 | score: 0.7478 | sources: ['SemanticModel']
approved | cefr: B1 | score: 0.7446 | sources: ['SemanticModel']
====================================================================================================
target: interested
target_cefr: A1
ranked after CEFR:
involved | cefr: B1 | score: 0.739 | sources: ['SemanticModel']
realized | cefr: None | score: 0.6538 | sources: ['SemanticModel']
====================================================================================================
target: however
target_cefr: A2
ranked after CEFR:
although | cefr: A2 | score: 1.2658 | sources: ['SemanticModel', 'LearnerCorpus']
therefore | cefr: B1 | score: 1.0824 | sources: ['SemanticModel', 'LearnerCorpus']
moreover | cefr: B1 | score: 1.0694 | sources: ['SemanticModel', 'LearnerCorpus']
though | cefr: A2 | score: 0.9802 | sources: ['SemanticModel']
otherwise | cefr: B1 | score: 0.9492 | sources: ['LearnerCorpus']
instead | cefr: A2 | score: 0.8017 | sources: ['SemanticModel']
====================================================================================================
target: thick
target_cefr: A1
ranked after CEFR:
tall | cefr: A1 | score: 0.7283 | sources: ['SemanticModel']
dark | cefr: A1 | score: 0.7154 | sources: ['SemanticModel']
yellow | cefr: A1 | score: 0.6688 | sources: ['SemanticModel']
dry | cefr: A1 | score: 0.6441 | sources: ['SemanticModel']
shiny | cefr: B1 | score: 0.6343 | sources: ['SemanticModel']
rough | cefr: B1 | score: 0.627 | sources: ['SemanticModel']
gray | cefr: None | score: 0.6214 | sources: ['SemanticModel']
large | cefr: A1 | score: 0.6214 | sources: ['SemanticModel']
sturdy | cefr: None | score: 0.6179 | sources: ['SemanticModel']
shallow | cefr: B1 | score: 0.6166 | sources: ['SemanticModel']
====================================================================================================
target: remind
target_cefr: A2
ranked after CEFR:
remember | cefr: A1 | score: 0.9686 | sources: ['SemanticModel', 'LearnerCorpus']
tell | cefr: A1 | score: 0.8075 | sources: ['SemanticModel']
ask | cefr: A1 | score: 0.7271 | sources: ['SemanticModel']
forget | cefr: A1 | score: 0.7242 | sources: ['SemanticModel']
wish | cefr: A1 | score: 0.7215 | sources: ['SemanticModel']
inform | cefr: B1 | score: 0.7188 | sources: ['SemanticModel']
impress | cefr: A2 | score: 0.7152 | sources: ['SemanticModel']
let | cefr: A1 | score: 0.6995 | sources: ['SemanticModel']
educate | cefr: B1 | score: 0.6993 | sources: ['SemanticModel']
motivate | cefr: B1 | score: 0.6986 | sources: ['SemanticModel']
====================================================================================================
target: observing
target_cefr: B1
ranked after CEFR:
monitoring | cefr: B1 | score: 0.6635 | sources: ['SemanticModel']
conducting | cefr: B1 | score: 0.6276 | sources: ['SemanticModel']
analyzing | cefr: None | score: 0.6042 | sources: ['SemanticModel']
photographing | cefr: A2 | score: 0.5732 | sources: ['SemanticModel']
witnessing | cefr: B1 | score: 0.5696 | sources: ['SemanticModel']
guiding | cefr: B1 | score: 0.5578 | sources: ['SemanticModel']
tracking | cefr: A2 | score: 0.5563 | sources: ['SemanticModel']
studying | cefr: A1 | score: 0.5546 | sources: ['SemanticModel']
surveying | cefr: A1 | score: 0.5478 | sources: ['SemanticModel']
simulating | cefr: None | score: 0.545 | sources: ['SemanticModel']
====================================================================================================
target: told
target_cefr: A1
ranked after CEFR:
spoke | cefr: A1 | score: 1.0432 | sources: ['SemanticModel', 'LearnerCorpus']
talked | cefr: A1 | score: 0.969 | sources: ['SemanticModel', 'LearnerCorpus']
insisted | cefr: B1 | score: 0.8098 | sources: ['SemanticModel']
informed | cefr: B1 | score: 0.7786 | sources: ['SemanticModel']
explained | cefr: A2 | score: 0.7618 | sources: ['SemanticModel']
met | cefr: A1 | score: 0.7581 | sources: ['SemanticModel']
acknowledged | cefr: B1 | score: 0.7578 | sources: ['SemanticModel']
warned | cefr: B1 | score: 0.7507 | sources: ['SemanticModel']
suggested | cefr: A2 | score: 0.7334 | sources: ['SemanticModel']
wanted | cefr: A1 | score: 0.7209 | sources: ['SemanticModel']
====================================================================================================
target: formed
target_cefr: A1
ranked after CEFR:
established | cefr: A2 | score: 0.7621 | sources: ['SemanticModel']
joined | cefr: A1 | score: 0.7618 | sources: ['SemanticModel']
created | cefr: A2 | score: 0.7543 | sources: ['SemanticModel']
incorporated | cefr: None | score: 0.7418 | sources: ['SemanticModel']
became | cefr: A1 | score: 0.6954 | sources: ['SemanticModel']
called | cefr: A1 | score: 0.6766 | sources: ['SemanticModel']
composed | cefr: B1 | score: 0.6659 | sources: ['SemanticModel']
renamed | cefr: None | score: 0.6557 | sources: ['SemanticModel']
began | cefr: A1 | score: 0.6523 | sources: ['SemanticModel']
led | cefr: A2 | score: 0.6464 | sources: ['SemanticModel']
====================================================================================================
target: introduced
target_cefr: A1
ranked after CEFR:
announced | cefr: B1 | score: 0.8928 | sources: ['SemanticModel', 'LearnerCorpus']
created | cefr: A2 | score: 0.748 | sources: ['SemanticModel']
modified | cefr: B1 | score: 0.7353 | sources: ['SemanticModel']
used | cefr: A2 | score: 0.7214 | sources: ['SemanticModel']
changed | cefr: A1 | score: 0.7199 | sources: ['SemanticModel']
designed | cefr: A1 | score: 0.7077 | sources: ['SemanticModel']
replaced | cefr: A2 | score: 0.7076 | sources: ['SemanticModel']
called | cefr: A1 | score: 0.7058 | sources: ['SemanticModel']
expanded | cefr: B1 | score: 0.7005 | sources: ['SemanticModel']
included | cefr: A2 | score: 0.6996 | sources: ['SemanticModel']
====================================================================================================
target: attracted
target_cefr: B1
ranked after CEFR:
garnered | cefr: None | score: 0.6696 | sources: ['SemanticModel']
encouraged | cefr: A2 | score: 0.6546 | sources: ['SemanticModel']
generated | cefr: B1 | score: 0.6508 | sources: ['SemanticModel']
grew | cefr: A1 | score: 0.6395 | sources: ['SemanticModel']
grown | cefr: A1 | score: 0.6331 | sources: ['SemanticModel']
spurred | cefr: B2 | score: 0.6324 | sources: ['SemanticModel']
devoted | cefr: B2 | score: 0.6182 | sources: ['SemanticModel']
brought | cefr: A1 | score: 0.6153 | sources: ['SemanticModel']
enjoyed | cefr: A1 | score: 0.612 | sources: ['SemanticModel']
aroused | cefr: B2 | score: 0.6058 | sources: ['SemanticModel']
====================================================================================================
target: out
target_cefr: A1
ranked after CEFR:
up | cefr: A1 | score: 1.1888 | sources: ['SemanticModel', 'LearnerCorpus']
down | cefr: A1 | score: 1.1282 | sources: ['SemanticModel', 'LearnerCorpus']
over | cefr: A1 | score: 1.1035 | sources: ['SemanticModel', 'LearnerCorpus']
off | cefr: A1 | score: 0.9223 | sources: ['SemanticModel']
back | cefr: A1 | score: 0.9183 | sources: ['SemanticModel']
away | cefr: A1 | score: 0.9084 | sources: ['SemanticModel']
into | cefr: A1 | score: 0.8989 | sources: ['SemanticModel']
on | cefr: A1 | score: 0.8199 | sources: ['SemanticModel']
from | cefr: A1 | score: 0.8173 | sources: ['SemanticModel']
around | cefr: A1 | score: 0.789 | sources: ['SemanticModel']
====================================================================================================
target: talk
target_cefr: A1
ranked after CEFR:
tell | cefr: A1 | score: 1.0678 | sources: ['SemanticModel', 'LearnerCorpus']
say | cefr: A1 | score: 0.9826 | sources: ['SemanticModel', 'LearnerCorpus']
want | cefr: A1 | score: 0.8067 | sources: ['SemanticModel']
call | cefr: A1 | score: 0.7963 | sources: ['SemanticModel']
listen | cefr: A1 | score: 0.7893 | sources: ['SemanticModel']
know | cefr: A1 | score: 0.7875 | sources: ['SemanticModel']
come | cefr: A1 | score: 0.7803 | sources: ['SemanticModel']
hear | cefr: A1 | score: 0.7691 | sources: ['SemanticModel']
go | cefr: A1 | score: 0.7654 | sources: ['SemanticModel']
let | cefr: A1 | score: 0.7625 | sources: ['SemanticModel']

In [60]:
# =========================
# БЛОК 9. Расширенный контекст текста
# =========================

def split_into_sentences(text: str) -> List[str]:
    """
    Делит полный текст на предложения через spaCy.
    """
    text = clean_text(text)

    if not text:
        return []

    doc = nlp(text)

    return [
        clean_text(sent.text)
        for sent in doc.sents
        if clean_text(sent.text)
    ]


def token_set_for_matching(text: str) -> set:
    """
    Делает набор лемм для мягкого сопоставления предложений.

    Это нужно на случай, если sentence_with_answer
    немного отличается от предложения внутри full_text.
    """
    doc = nlp(clean_text(text).lower())

    return {
        token.lemma_
        for token in doc
        if token.is_alpha and token.text not in stop_words
    }


def find_target_sentence_index(
    sentences: List[str],
    sentence_with_answer: str,
    target: str
) -> int:
    """
    Находит индекс предложения с target внутри полного текста.

    Сначала ищем target как отдельное слово.
    Если таких предложений несколько, выбираем то, которое больше всего
    похоже на sentence_with_answer по пересечению лемм.
    """
    if not sentences:
        return -1

    target = clean_text(target).lower()
    answer_tokens = token_set_for_matching(sentence_with_answer)

    best_index = -1
    best_score = -1

    for i, sentence in enumerate(sentences):
        sentence_clean = clean_text(sentence)
        sentence_lower = sentence_clean.lower()

        has_target = bool(
            re.search(
                r"\b" + re.escape(target) + r"\b",
                sentence_lower,
                flags=re.IGNORECASE
            )
        )

        sentence_tokens = token_set_for_matching(sentence_clean)
        overlap = len(answer_tokens & sentence_tokens)

        # target важнее, чем просто лексическое пересечение
        score = overlap + (10 if has_target else 0)

        if score > best_score:
            best_score = score
            best_index = i

    return best_index


def get_extended_context(
    full_text: str,
    sentence_with_answer: str,
    target: str,
    window: int = 1
) -> str:
    """
    Возвращает расширенный контекст:
    предложение с target + window предложений слева и справа.
    """
    sentences = split_into_sentences(full_text)

    if not sentences:
        return clean_text(sentence_with_answer)

    target_index = find_target_sentence_index(
        sentences=sentences,
        sentence_with_answer=sentence_with_answer,
        target=target
    )

    if target_index == -1:
        return clean_text(sentence_with_answer)

    start = max(0, target_index - window)
    end = min(len(sentences), target_index + window + 1)

    return clean_text(
        " ".join(sentences[start:end])
    )

In [61]:
# =========================
# БЛОК 9. Применяем расширенный контекст
# =========================

CONTEXT_WINDOW = 1

df["extended_context"] = df.apply(
    lambda row: get_extended_context(
        full_text=row["text_clean"],
        sentence_with_answer=row["sentence_clean"],
        target=row["target_clean"],
        window=CONTEXT_WINDOW
    ),
    axis=1
)

df["extended_context_length_words"] = df["extended_context"].apply(
    lambda text: len(clean_text(text).split())
)

df[
    [
        "target_clean",
        "sentence_clean",
        "extended_context",
        "extended_context_length_words"
    ]
].head(10)

,target_clean,sentence_clean,extended_context,extended_context_length_words
0,announced,"Last week, our coach Mr Brown announced we wer...","Occasionally, the team took field trips to pla...",57
1,interested,We weren't all that interested in the outdoors.,"Simon is my best friend, and the two of us had...",49
2,however,"However, Mr Brown claimed that we'd really enj...",We weren't all that interested in the outdoors...,40
3,thick,"Now we were in a state park, marching through ...",Simon and I were sure we'd rather be back home...,59
4,remind,"Doesn't its shape remind you of an elephant?"" ...","I looked around, shouting, ""Check out that tre...",21
5,observing,"You don't see stuff like that in the city, now...","You don't see stuff like that in the city, now...",48
6,told,"Out here, away from the city, I was starting t...",We were beginning to see the amazing things ar...,33
7,formed,I formed the habit now of going every Saturday...,"I never took Olivia to the theatre, but it was...",38
8,introduced,It was George who introduced me to Olivia Nelson.,I formed the habit now of going every Saturday...,42
9,attracted,"She was not very beautiful but she was tall, v...","She was not very beautiful but she was tall, v...",29

In [62]:
# =========================
# БЛОК 9. Диагностика расширенного контекста
# =========================

for _, row in df.head(8).iterrows():
    print("=" * 100)
    print("target:", row["target_clean"])
    print("sentence:")
    print(row["sentence_clean"])
    print("\nextended_context:")
    print(row["extended_context"])
    print("words:", row["extended_context_length_words"])

====================================================================================================
target: announced
sentence:
Last week, our coach Mr Brown announced we were going on a hike through a forest in a state park.

extended_context:
Occasionally, the team took field trips to places outside of our neighbourhood on the weekends. Last week, our coach Mr Brown announced we were going on a hike through a forest in a state park. Simon is my best friend, and the two of us had both liked the trips to the museums, plays, and basketball games.
words: 57
====================================================================================================
target: interested
sentence:
We weren't all that interested in the outdoors.

extended_context:
Simon is my best friend, and the two of us had both liked the trips to the museums, plays, and basketball games. We weren't all that interested in the outdoors. However, Mr Brown claimed that we'd really enjoy discovering how amazing nature can be-especially for the big city kids.
words: 49
====================================================================================================
target: however
sentence:
However, Mr Brown claimed that we'd really enjoy discovering how amazing nature can be-especially for the big city kids.

extended_context:
We weren't all that interested in the outdoors. However, Mr Brown claimed that we'd really enjoy discovering how amazing nature can be-especially for the big city kids. Simon and I were sure we'd rather be back home playing video games.
words: 40
====================================================================================================
target: thick
sentence:
Now we were in a state park, marching through woods as thick as a grizzly bear's fur.

extended_context:
Simon and I were sure we'd rather be back home playing video games. Now we were in a state park, marching through woods as thick as a grizzly bear's fur. Our group of 12 kids had been hiking for a good 30 minutes when Simon and I grew bored and stepped away from the group to take some pictures.
words: 59
====================================================================================================
target: remind
sentence:
Doesn't its shape remind you of an elephant?" "Ha!

extended_context:
I looked around, shouting, "Check out that tree - it's kinda cool. Doesn't its shape remind you of an elephant?" "Ha!
words: 21
====================================================================================================
target: observing
sentence:
You don't see stuff like that in the city, now do you?" For the next few minutes, we got caught up in observing flowers, leaves, animals, and little caves we hadn't seen before.

extended_context:
You don't see stuff like that in the city, now do you?" For the next few minutes, we got caught up in observing flowers, leaves, animals, and little caves we hadn't seen before. The more we opened up to the forest, the more it opened up to us.
words: 48
====================================================================================================
target: told
sentence:
Out here, away from the city, I was starting to get what Mr Brown had told us about how wonderful nature could be.

extended_context:
We were beginning to see the amazing things around us. Out here, away from the city, I was starting to get what Mr Brown had told us about how wonderful nature could be.
words: 33
====================================================================================================
target: formed
sentence:
I formed the habit now of going every Saturday night, usually alone, sometimes with George.

extended_context:
I never took Olivia to the theatre, but it was there I met her. I formed the habit now of going every Saturday night, usually alone, sometimes with George. It was George who introduced me to Olivia Nelson.
words: 38

In [63]:
# =========================
# БЛОК 10. Настройки BERT-фильтра
# =========================

USE_BERT_FILTER = True

BERT_MODEL_NAME = "distilroberta-base"

# Если кандидат имеет вероятность выше этой доли от правильного ответа,
# он считается слишком подходящим к контексту.
BERT_MAX_RELATIVE_TO_TARGET = 0.45

# Если BERT вообще почти не знает это слово в контексте, оставляем его.
# Поэтому нижний порог не делаем слишком жестким.
BERT_MIN_CANDIDATE_SCORE = 0.0

print("USE_BERT_FILTER:", USE_BERT_FILTER)

USE_BERT_FILTER: True

In [64]:
# =========================
# БЛОК 10. Загрузка masked language model
# =========================

if USE_BERT_FILTER:
    from transformers import pipeline

    fill_mask = pipeline(
        "fill-mask",
        model=BERT_MODEL_NAME
    )

    print("BERT model loaded:", BERT_MODEL_NAME)
else:
    fill_mask = None
    print("BERT filter выключен.")

config.json:   0%|          | 0.00/480 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors:   0%|          | 0.00/331M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/106 [00:00<?, ?it/s]

RobertaForMaskedLM LOAD REPORT from: distilroberta-base
Key                         | Status     |  |
----------------------------+------------+--+-
roberta.pooler.dense.weight | UNEXPECTED |  |
roberta.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

BERT model loaded: distilroberta-base

In [65]:
# =========================
# БЛОК 10. Маскировка target в extended_context
# =========================

def mask_target_in_context(
    context: str,
    target: str,
    mask_token: str = "<mask>"
) -> str:
    """
    Заменяет первое вхождение target в extended_context на <mask>.
    """
    context = clean_text(context)
    target = clean_text(target)

    pattern = r"\b" + re.escape(target) + r"\b"

    masked = re.sub(
        pattern,
        mask_token,
        context,
        count=1,
        flags=re.IGNORECASE
    )

    # Если target почему-то не найден, добавляем mask перед контекстом.
    if masked == context:
        masked = f"{mask_token} {context}"

    return masked


def shorten_masked_context(
    masked_context: str,
    mask_token: str = "<mask>",
    window_words: int = 80
) -> str:
    """
    Обрезает слишком длинный контекст вокруг <mask>,
    чтобы BERT не получал чрезмерно длинный ввод.
    """
    tokens = clean_text(masked_context).split()

    if mask_token not in tokens:
        return clean_text(masked_context)

    mask_index = tokens.index(mask_token)

    start = max(
        0,
        mask_index - window_words
    )

    end = min(
        len(tokens),
        mask_index + window_words + 1
    )

    return " ".join(tokens[start:end])


df["masked_extended_context"] = df.apply(
    lambda row: shorten_masked_context(
        mask_target_in_context(
            row["extended_context"],
            row["target_clean"]
        )
    ),
    axis=1
)

df[
    [
        "target_clean",
        "masked_extended_context"
    ]
].head()

  target_clean                            masked_extended_context
0    announced  Occasionally, the team took field trips to pla...
1   interested  Simon is my best friend, and the two of us had...
2      however  We weren't all that interested in the outdoors...
3        thick  Simon and I were sure we'd rather be back home...
4       remind  I looked around, shouting, "Check out that tre...

In [66]:
# =========================
# БЛОК 10. BERT score
# =========================

def bert_candidate_score(masked_context: str, candidate: str) -> float:
    """
    Возвращает вероятность candidate в позиции <mask>.
    Для multi-word candidates возвращаем 0.0, потому что fill-mask
    работает с одним mask token.
    """
    if not USE_BERT_FILTER:
        return 0.0

    candidate = clean_text(candidate).lower()

    if not candidate:
        return 0.0

    if len(candidate.split()) > 1:
        return 0.0

    try:
        result = fill_mask(
            masked_context,
            targets=[candidate]
        )

        if isinstance(result, list) and result:
            return float(
                result[0].get(
                    "score",
                    0.0
                )
            )

    except Exception:
        return 0.0

    return 0.0

In [67]:
# =========================
# БЛОК 10. Сравнение кандидата с правильным ответом
# =========================

def compute_bert_scores_for_row(row) -> Dict:
    """
    Считает BERT-score:
    - для target;
    - для каждого кандидата после CEFR-фильтра.
    """
    masked_context = row["masked_extended_context"]

    target = row["target_clean"]

    target_score = bert_candidate_score(
        masked_context,
        target
    )

    # Чтобы не делить на 0
    target_score = max(
        target_score,
        1e-12
    )

    candidate_scores = {}

    for item in row["ranked_candidates_cefr"]:
        candidate = item["candidate"]

        candidate_score = bert_candidate_score(
            masked_context,
            candidate
        )

        candidate_scores[candidate] = {
            "candidate_score": candidate_score,
            "target_score": target_score,
            "relative_to_target": candidate_score / target_score
        }

    return {
        "target_score": target_score,
        "candidate_scores": candidate_scores
    }


if USE_BERT_FILTER:
    df["bert_scores"] = df.apply(
        compute_bert_scores_for_row,
        axis=1
    )
else:
    df["bert_scores"] = [
        {
            "target_score": None,
            "candidate_scores": {}
        }
        for _ in range(len(df))
    ]

print("BERT scores computed.")

The specified target token `presented` does not exist in the model vocabulary. Replacing with `present`.
The specified target token `agreed` does not exist in the model vocabulary. Replacing with `ag`.
The specified target token `decided` does not exist in the model vocabulary. Replacing with `dec`.
The specified target token `extended` does not exist in the model vocabulary. Replacing with `ext`.
The specified target token `unveiled` does not exist in the model vocabulary. Replacing with `un`.
The specified target token `proposed` does not exist in the model vocabulary. Replacing with `prop`.
The specified target token `promised` does not exist in the model vocabulary. Replacing with `prom`.
The specified target token `scheduled` does not exist in the model vocabulary. Replacing with `sc`.
The specified target token `rejected` does not exist in the model vocabulary. Replacing with `re`.
The specified target token `launched` does not exist in the model vocabulary. Replacing with `laun`.
The specified target token `offered` does not exist in the model vocabulary. Replacing with `off`.
The specified target token `promoted` does not exist in the model vocabulary. Replacing with `prom`.
The specified target token `suggested` does not exist in the model vocabulary. Replacing with `suggest`.
The specified target token `hoped` does not exist in the model vocabulary. Replacing with `hop`.
The specified target token `declined` does not exist in the model vocabulary. Replacing with `decl`.
The specified target token `realized` does not exist in the model vocabulary. Replacing with `real`.
The specified target token `however` does not exist in the model vocabulary. Replacing with `how`.
The specified target token `therefore` does not exist in the model vocabulary. Replacing with `there`.
The specified target token `moreover` does not exist in the model vocabulary. Replacing with `more`.
The specified target token `otherwise` does not exist in the model vocabulary. Replacing with `other`.
The specified target token `thick` does not exist in the model vocabulary. Replacing with `th`.
The specified target token `shiny` does not exist in the model vocabulary. Replacing with `sh`.
The specified target token `sturdy` does not exist in the model vocabulary. Replacing with `st`.
The specified target token `shallow` does not exist in the model vocabulary. Replacing with `sh`.
The specified target token `loose` does not exist in the model vocabulary. Replacing with `lo`.
The specified target token `slick` does not exist in the model vocabulary. Replacing with `sl`.
The specified target token `crisp` does not exist in the model vocabulary. Replacing with `c`.
The specified target token `reddish` does not exist in the model vocabulary. Replacing with `redd`.
The specified target token `remind` does not exist in the model vocabulary. Replacing with `rem`.
The specified target token `forget` does not exist in the model vocabulary. Replacing with `for`.
The specified target token `wish` does not exist in the model vocabulary. Replacing with `w`.
The specified target token `inform` does not exist in the model vocabulary. Replacing with `in`.
The specified target token `impress` does not exist in the model vocabulary. Replacing with `im`.
The specified target token `educate` does not exist in the model vocabulary. Replacing with `educ`.
The specified target token `motivate` does not exist in the model vocabulary. Replacing with `mot`.
The specified target token `understand` does not exist in the model vocabulary. Replacing with `under`.
The specified target token `listen` does not exist in the model vocabulary. Replacing with `list`.
The specified target token `imagine` does not exist in the model vocabulary. Replacing with `im`.
The specified target token `pretend` does not exist in the model vocabulary. Replacing with `pret`.
The specified target token `urge` does not exist in the model vocabulary. Replacing with `ur`.
The specified target token `advise` does not exist in the model vocabulary. Replacing with `adv`.
The specified target token `explain` does not exist in the model vocabulary. Replacing with `expl`.
The specified target token `hear` does not exist in the model vocabulary. Replacing with `he`.
The specified target token `appreciate` does not exist in the model vocabulary. Replacing with `app`.
The specified target token `worry` does not exist in the model vocabulary. Replacing with `w`.
The specified target token `convey` does not exist in the model vocabulary. Replacing with `con`.
The specified target token `realize` does not exist in the model vocabulary. Replacing with `real`.
The specified target token `acknowledge` does not exist in the model vocabulary. Replacing with `ack`.
The specified target token `reiterate` does not exist in the model vocabulary. Replacing with `re`.
The specified target token `implore` does not exist in the model vocabulary. Replacing with `impl`.
The specified target token `recall` does not exist in the model vocabulary. Replacing with `rec`.
The specified target token `emphasize` does not exist in the model vocabulary. Replacing with `em`.
The specified target token `annoy` does not exist in the model vocabulary. Replacing with `ann`.
The specified target token `bother` does not exist in the model vocabulary. Replacing with `b`.
The specified target token `disappoint` does not exist in the model vocabulary. Replacing with `dis`.
The specified target token `happen` does not exist in the model vocabulary. Replacing with `h`.
The specified target token `revise` does not exist in the model vocabulary. Replacing with `rev`.
The specified target token `observing` does not exist in the model vocabulary. Replacing with `ob`.
The specified target token `monitoring` does not exist in the model vocabulary. Replacing with `monitor`.
The specified target token `conducting` does not exist in the model vocabulary. Replacing with `conduct`.
The specified target token `analyzing` does not exist in the model vocabulary. Replacing with `analy`.
The specified target token `photographing` does not exist in the model vocabulary. Replacing with `phot`.
The specified target token `witnessing` does not exist in the model vocabulary. Replacing with `w`.
The specified target token `guiding` does not exist in the model vocabulary. Replacing with `gu`.
The specified target token `studying` does not exist in the model vocabulary. Replacing with `stud`.
The specified target token `surveying` does not exist in the model vocabulary. Replacing with `sur`.
The specified target token `simulating` does not exist in the model vocabulary. Replacing with `sim`.
The specified target token `evaluating` does not exist in the model vocabulary. Replacing with `eval`.
The specified target token `analysing` does not exist in the model vocabulary. Replacing with `an`.
The specified target token `assessing` does not exist in the model vocabulary. Replacing with `ass`.
The specified target token `interacting` does not exist in the model vocabulary. Replacing with `inter`.
The specified target token `demonstrating` does not exist in the model vocabulary. Replacing with `demon`.
The specified target token `examining` does not exist in the model vocabulary. Replacing with `ex`.
The specified target token `describing` does not exist in the model vocabulary. Replacing with `desc`.
The specified target token `interpreting` does not exist in the model vocabulary. Replacing with `inter`.
The specified target token `enforcing` does not exist in the model vocabulary. Replacing with `en`.
The specified target token `scrutinizing` does not exist in the model vocabulary. Replacing with `sc`.
The specified target token `discussing` does not exist in the model vocabulary. Replacing with `disc`.
The specified target token `fasting` does not exist in the model vocabulary. Replacing with `fast`.
The specified target token `listening` does not exist in the model vocabulary. Replacing with `list`.
The specified target token `practicing` does not exist in the model vocabulary. Replacing with `pract`.
The specified target token `adhering` does not exist in the model vocabulary. Replacing with `ad`.
The specified target token `recreating` does not exist in the model vocabulary. Replacing with `rec`.
The specified target token `fulfilling` does not exist in the model vocabulary. Replacing with `ful`.
The specified target token `waking` does not exist in the model vocabulary. Replacing with `w`.
The specified target token `patrolling` does not exist in the model vocabulary. Replacing with `pat`.
The specified target token `meditating` does not exist in the model vocabulary. Replacing with `med`.
The specified target token `inspecting` does not exist in the model vocabulary. Replacing with `ins`.
The specified target token `comparing` does not exist in the model vocabulary. Replacing with `comp`.
The specified target token `gathering` does not exist in the model vocabulary. Replacing with `g`.
The specified target token `recognizing` does not exist in the model vocabulary. Replacing with `recogn`.
The specified target token `praying` does not exist in the model vocabulary. Replacing with `pr`.
The specified target token `searching` does not exist in the model vocabulary. Replacing with `search`.
The specified target token `launching` does not exist in the model vocabulary. Replacing with `laun`.
The specified target token `defining` does not exist in the model vocabulary. Replacing with `def`.
The specified target token `interviewing` does not exist in the model vocabulary. Replacing with `inter`.
The specified target token `exercising` does not exist in the model vocabulary. Replacing with `ex`.
The specified target token `researching` does not exist in the model vocabulary. Replacing with `research`.
The specified target token `viewing` does not exist in the model vocabulary. Replacing with `view`.
The specified target token `establishing` does not exist in the model vocabulary. Replacing with `establish`.
The specified target token `communicating` does not exist in the model vocabulary. Replacing with `commun`.
The specified target token `exploring` does not exist in the model vocabulary. Replacing with `expl`.
The specified target token `foraging` does not exist in the model vocabulary. Replacing with `for`.
The specified target token `imagining` does not exist in the model vocabulary. Replacing with `imag`.
The specified target token `spoke` does not exist in the model vocabulary. Replacing with `sp`.
The specified target token `talked` does not exist in the model vocabulary. Replacing with `talk`.
The specified target token `insisted` does not exist in the model vocabulary. Replacing with `ins`.
The specified target token `explained` does not exist in the model vocabulary. Replacing with `expl`.
The specified target token `acknowledged` does not exist in the model vocabulary. Replacing with `ack`.
The specified target token `warned` does not exist in the model vocabulary. Replacing with `warn`.
The specified target token `suggested` does not exist in the model vocabulary. Replacing with `suggest`.
The specified target token `wanted` does not exist in the model vocabulary. Replacing with `w`.
The specified target token `noted` does not exist in the model vocabulary. Replacing with `not`.
The specified target token `stressed` does not exist in the model vocabulary. Replacing with `st`.
The specified target token `contacted` does not exist in the model vocabulary. Replacing with `cont`.
The specified target token `hoped` does not exist in the model vocabulary. Replacing with `hop`.
The specified target token `knew` does not exist in the model vocabulary. Replacing with `k`.
The specified target token `complained` does not exist in the model vocabulary. Replacing with `compl`.
The specified target token `urged` does not exist in the model vocabulary. Replacing with `ur`.
The specified target token `commented` does not exist in the model vocabulary. Replacing with `com`.
The specified target token `gave` does not exist in the model vocabulary. Replacing with `g`.
The specified target token `questioned` does not exist in the model vocabulary. Replacing with `quest`.
The specified target token `refused` does not exist in the model vocabulary. Replacing with `ref`.
The specified target token `incorporated` does not exist in the model vocabulary. Replacing with `inc`.
The specified target token `became` does not exist in the model vocabulary. Replacing with `bec`.
The specified target token `composed` does not exist in the model vocabulary. Replacing with `comp`.
The specified target token `renamed` does not exist in the model vocabulary. Replacing with `ren`.
The specified target token `began` does not exist in the model vocabulary. Replacing with `be`.
The specified target token `disbanded` does not exist in the model vocabulary. Replacing with `dis`.
The specified target token `dissolved` does not exist in the model vocabulary. Replacing with `d`.
The specified target token `entered` does not exist in the model vocabulary. Replacing with `ent`.
The specified target token `amalgamated` does not exist in the model vocabulary. Replacing with `am`.
The specified target token `separated` does not exist in the model vocabulary. Replacing with `separ`.
The specified target token `consisted` does not exist in the model vocabulary. Replacing with `cons`.
The specified target token `moved` does not exist in the model vocabulary. Replacing with `m`.
The specified target token `introduced` does not exist in the model vocabulary. Replacing with `introdu`.
The specified target token `replaced` does not exist in the model vocabulary. Replacing with `re`.
The specified target token `expanded` does not exist in the model vocabulary. Replacing with `exp`.
The specified target token `included` does not exist in the model vocabulary. Replacing with `in`.
The specified target token `passed` does not exist in the model vocabulary. Replacing with `pass`.
The specified target token `became` does not exist in the model vocabulary. Replacing with `bec`.
The specified target token `incorporated` does not exist in the model vocabulary. Replacing with `inc`.
The specified target token `referred` does not exist in the model vocabulary. Replacing with `re`.
The specified target token `offered` does not exist in the model vocabulary. Replacing with `off`.
The specified target token `intended` does not exist in the model vocabulary. Replacing with `int`.
The specified target token `enacted` does not exist in the model vocabulary. Replacing with `en`.
The specified target token `featured` does not exist in the model vocabulary. Replacing with `f`.
The specified target token `followed` does not exist in the model vocabulary. Replacing with `follow`.
The specified target token `welcomed` does not exist in the model vocabulary. Replacing with `w`.
The specified target token `attracted` does not exist in the model vocabulary. Replacing with `att`.
The specified target token `garnered` does not exist in the model vocabulary. Replacing with `gar`.
The specified target token `encouraged` does not exist in the model vocabulary. Replacing with `enc`.
The specified target token `grew` does not exist in the model vocabulary. Replacing with `g`.
The specified target token `spurred` does not exist in the model vocabulary. Replacing with `sp`.
The specified target token `devoted` does not exist in the model vocabulary. Replacing with `dev`.
The specified target token `brought` does not exist in the model vocabulary. Replacing with `b`.
The specified target token `enjoyed` does not exist in the model vocabulary. Replacing with `en`.
The specified target token `aroused` does not exist in the model vocabulary. Replacing with `ar`.
The specified target token `impressed` does not exist in the model vocabulary. Replacing with `imp`.
The specified target token `viewed` does not exist in the model vocabulary. Replacing with `view`.
The specified target token `offered` does not exist in the model vocabulary. Replacing with `off`.
The specified target token `listen` does not exist in the model vocabulary. Replacing with `list`.
The specified target token `hear` does not exist in the model vocabulary. Replacing with `he`.
The specified target token `understand` does not exist in the model vocabulary. Replacing with `under`.
The specified target token `wants` does not exist in the model vocabulary. Replacing with `w`.
The specified target token `imagine` does not exist in the model vocabulary. Replacing with `im`.
The specified target token `forget` does not exist in the model vocabulary. Replacing with `for`.
The specified target token `worry` does not exist in the model vocabulary. Replacing with `w`.
The specified target token `expect` does not exist in the model vocabulary. Replacing with `ex`.
The specified target token `discovered` does not exist in the model vocabulary. Replacing with `disc`.
The specified target token `unearthed` does not exist in the model vocabulary. Replacing with `une`.
The specified target token `believed` does not exist in the model vocabulary. Replacing with `bel`.
The specified target token `invented` does not exist in the model vocabulary. Replacing with `in`.
The specified target token `uncovered` does not exist in the model vocabulary. Replacing with `unc`.
The specified target token `explored` does not exist in the model vocabulary. Replacing with `expl`.
The specified target token `excavated` does not exist in the model vocabulary. Replacing with `exc`.
The specified target token `traced` does not exist in the model vocabulary. Replacing with `tr`.
The specified target token `buried` does not exist in the model vocabulary. Replacing with `bur`.
The specified target token `examined` does not exist in the model vocabulary. Replacing with `ex`.
The specified target token `recovered` does not exist in the model vocabulary. Replacing with `rec`.
The specified target token `taken` does not exist in the model vocabulary. Replacing with `t`.
The specified target token `disappeared` does not exist in the model vocabulary. Replacing with `dis`.
The specified target token `retrieved` does not exist in the model vocabulary. Replacing with `ret`.
The specified target token `collected` does not exist in the model vocabulary. Replacing with `col`.
The specified target token `searched` does not exist in the model vocabulary. Replacing with `se`.
The specified target token `removed` does not exist in the model vocabulary. Replacing with `rem`.
The specified target token `spotted` does not exist in the model vocabulary. Replacing with `sp`.
The specified target token `destroyed` does not exist in the model vocabulary. Replacing with `destroy`.
The specified target token `survived` does not exist in the model vocabulary. Replacing with `surv`.
The specified target token `knew` does not exist in the model vocabulary. Replacing with `k`.
The specified target token `abandoned` does not exist in the model vocabulary. Replacing with `ab`.
The specified target token `concluded` does not exist in the model vocabulary. Replacing with `con`.
The specified target token `obtained` does not exist in the model vocabulary. Replacing with `ob`.
The specified target token `idea` does not exist in the model vocabulary. Replacing with `ide`.
The specified target token `explanation` does not exist in the model vocabulary. Replacing with `ex`.
The specified target token `possibility` does not exist in the model vocabulary. Replacing with `p`.
The specified target token `notion` does not exist in the model vocabulary. Replacing with `not`.
The specified target token `recognised` does not exist in the model vocabulary. Replacing with `recogn`.
The specified target token `regarded` does not exist in the model vocabulary. Replacing with `reg`.

BERT scores computed.

In [68]:
# =========================
# БЛОК 10. Диагностика BERT-score
# =========================

for _, row in df.head(8).iterrows():
    print("=" * 100)
    print("target:", row["target_clean"])
    print("masked context:")
    print(row["masked_extended_context"])
    print("target_score:", row["bert_scores"]["target_score"])

    print("candidate scores:")

    for item in row["ranked_candidates_cefr"][:8]:
        candidate = item["candidate"]

        scores = row["bert_scores"]["candidate_scores"].get(
            candidate,
            {}
        )

        print(
            candidate,
            "| cand_score:",
            round(scores.get("candidate_score", 0.0), 8),
            "| relative:",
            round(scores.get("relative_to_target", 0.0), 4),
            "| sources:",
            item["sources"]
        )

====================================================================================================
target: announced
masked context:
Occasionally, the team took field trips to places outside of our neighbourhood on the weekends. Last week, our coach Mr Brown <mask> we were going on a hike through a forest in a state park. Simon is my best friend, and the two of us had both liked the trips to the museums, plays, and basketball games.
target_score: 0.0006681207451038063
candidate scores:
presented | cand_score: 0.0 | relative: 0.0 | sources: ['LearnerCorpus']
agreed | cand_score: 6e-08 | relative: 0.0001 | sources: ['SemanticModel']
planned | cand_score: 0.0 | relative: 0.0 | sources: ['SemanticModel']
decided | cand_score: 0.0 | relative: 0.0 | sources: ['SemanticModel']
extended | cand_score: 0.0 | relative: 0.0 | sources: ['LearnerCorpus']
expected | cand_score: 0.0 | relative: 0.0 | sources: ['SemanticModel']
unveiled | cand_score: 0.0 | relative: 0.0 | sources: ['SemanticModel']
proposed | cand_score: 0.0 | relative: 0.0 | sources: ['SemanticModel']
====================================================================================================
target: interested
masked context:
Simon is my best friend, and the two of us had both liked the trips to the museums, plays, and basketball games. We weren't all that <mask> in the outdoors. However, Mr Brown claimed that we'd really enjoy discovering how amazing nature can be-especially for the big city kids.
target_score: 2.008183037105482e-05
candidate scores:
involved | cand_score: 1.6e-07 | relative: 0.0077 | sources: ['SemanticModel']
realized | cand_score: 0.0 | relative: 0.0 | sources: ['SemanticModel']
====================================================================================================
target: however
masked context:
We weren't all that interested in the outdoors. <mask>, Mr Brown claimed that we'd really enjoy discovering how amazing nature can be-especially for the big city kids. Simon and I were sure we'd rather be back home playing video games.
target_score: 2.1621238133207044e-09
candidate scores:
although | cand_score: 8e-08 | relative: 36.3386 | sources: ['SemanticModel', 'LearnerCorpus']
therefore | cand_score: 0.0 | relative: 0.0159 | sources: ['SemanticModel', 'LearnerCorpus']
moreover | cand_score: 1e-08 | relative: 2.4879 | sources: ['SemanticModel', 'LearnerCorpus']
though | cand_score: 6e-08 | relative: 27.2251 | sources: ['SemanticModel']
otherwise | cand_score: 0.0 | relative: 0.0325 | sources: ['LearnerCorpus']
instead | cand_score: 1.28e-06 | relative: 592.4943 | sources: ['SemanticModel']
====================================================================================================
target: thick
masked context:
Simon and I were sure we'd rather be back home playing video games. Now we were in a state park, marching through woods as <mask> as a grizzly bear's fur. Our group of 12 kids had been hiking for a good 30 minutes when Simon and I grew bored and stepped away from the group to take some pictures.
target_score: 9.259109035042457e-09
candidate scores:
tall | cand_score: 1.4e-07 | relative: 15.0078 | sources: ['SemanticModel']
dark | cand_score: 3e-08 | relative: 3.5776 | sources: ['SemanticModel']
yellow | cand_score: 0.0 | relative: 0.0339 | sources: ['SemanticModel']
dry | cand_score: 2e-08 | relative: 1.8843 | sources: ['SemanticModel']
shiny | cand_score: 2e-08 | relative: 1.8363 | sources: ['SemanticModel']
rough | cand_score: 4e-08 | relative: 4.7453 | sources: ['SemanticModel']
gray | cand_score: 0.0 | relative: 0.2655 | sources: ['SemanticModel']
large | cand_score: 3e-08 | relative: 2.9287 | sources: ['SemanticModel']
====================================================================================================
target: remind
masked context:
I looked around, shouting, "Check out that tree - it's kinda cool. Doesn't its shape <mask> you of an elephant?" "Ha!
target_score: 1e-12
candidate scores:
remember | cand_score: 0.0 | relative: 0.1821 | sources: ['SemanticModel', 'LearnerCorpus']
tell | cand_score: 1e-08 | relative: 12780.1663 | sources: ['SemanticModel']
ask | cand_score: 0.0 | relative: 4.1016 | sources: ['SemanticModel']
forget | cand_score: 0.0 | relative: 0.7387 | sources: ['SemanticModel']
wish | cand_score: 0.0 | relative: 0.5128 | sources: ['SemanticModel']
inform | cand_score: 0.0 | relative: 53.6885 | sources: ['SemanticModel']
impress | cand_score: 0.0 | relative: 3.3846 | sources: ['SemanticModel']
let | cand_score: 0.0 | relative: 1.4379 | sources: ['SemanticModel']
====================================================================================================
target: observing
masked context:
You don't see stuff like that in the city, now do you?" For the next few minutes, we got caught up in <mask> flowers, leaves, animals, and little caves we hadn't seen before. The more we opened up to the forest, the more it opened up to us.
target_score: 1.6501070509988836e-09
candidate scores:
monitoring | cand_score: 0.0 | relative: 0.0001 | sources: ['SemanticModel']
conducting | cand_score: 0.0 | relative: 0.0 | sources: ['SemanticModel']
analyzing | cand_score: 0.0 | relative: 0.0001 | sources: ['SemanticModel']
photographing | cand_score: 0.0 | relative: 0.0177 | sources: ['SemanticModel']
witnessing | cand_score: 2e-08 | relative: 9.6147 | sources: ['SemanticModel']
guiding | cand_score: 0.0 | relative: 0.0315 | sources: ['SemanticModel']
tracking | cand_score: 0.0 | relative: 0.9195 | sources: ['SemanticModel']
studying | cand_score: 0.0 | relative: 0.0046 | sources: ['SemanticModel']
====================================================================================================
target: told
masked context:
We were beginning to see the amazing things around us. Out here, away from the city, I was starting to get what Mr Brown had <mask> us about how wonderful nature could be.
target_score: 2.372269045736175e-05
candidate scores:
spoke | cand_score: 0.0 | relative: 0.0 | sources: ['SemanticModel', 'LearnerCorpus']
talked | cand_score: 0.0 | relative: 0.0 | sources: ['SemanticModel', 'LearnerCorpus']
insisted | cand_score: 0.0 | relative: 0.0 | sources: ['SemanticModel']
informed | cand_score: 2e-08 | relative: 0.0007 | sources: ['SemanticModel']
explained | cand_score: 0.0 | relative: 0.0 | sources: ['SemanticModel']
met | cand_score: 0.0 | relative: 0.0 | sources: ['SemanticModel']
acknowledged | cand_score: 0.0 | relative: 0.0 | sources: ['SemanticModel']
warned | cand_score: 0.0 | relative: 0.0002 | sources: ['SemanticModel']
====================================================================================================
target: formed
masked context:
I never took Olivia to the theatre, but it was there I met her. I <mask> the habit now of going every Saturday night, usually alone, sometimes with George. It was George who introduced me to Olivia Nelson.
target_score: 2.946823762783879e-08
candidate scores:
established | cand_score: 1e-08 | relative: 0.3746 | sources: ['SemanticModel']
joined | cand_score: 0.0 | relative: 0.1451 | sources: ['SemanticModel']
created | cand_score: 1e-08 | relative: 0.262 | sources: ['SemanticModel']
incorporated | cand_score: 0.0 | relative: 0.0215 | sources: ['SemanticModel']
became | cand_score: 0.0 | relative: 0.1566 | sources: ['SemanticModel']
called | cand_score: 0.0 | relative: 0.1672 | sources: ['SemanticModel']
composed | cand_score: 0.0 | relative: 0.0002 | sources: ['SemanticModel']
renamed | cand_score: 1.64e-06 | relative: 55.6301 | sources: ['SemanticModel']

In [69]:
# =========================
# БЛОК 10.1. Надежный BERT-фильтр
# =========================

BERT_MIN_RELIABLE_TARGET_SCORE = 1e-7
BERT_MAX_RELATIVE_TO_TARGET = 0.45

PROTECTED_BERT_SOURCES = {
    "CurrentGoldEGE",
    "LearnerCorpus"
}


def bert_filter_reason(item: Dict, row) -> Optional[str]:
    """
    Возвращает причину удаления кандидата через BERT.

    BERT-фильтр применяем осторожно:
    - не удаляем gold / learner candidates;
    - не используем relative score, если target_score слишком маленький;
    - удаляем только кандидаты, которые почти так же вероятны,
      как правильный ответ в расширенном контексте.
    """
    candidate = item["candidate"]
    sources = set(item["sources"])

    # Реальные дистракторы и learner errors не трогаем BERT-фильтром.
    if sources & PROTECTED_BERT_SOURCES:
        return None

    if not USE_BERT_FILTER:
        return None

    bert_info = row["bert_scores"]
    target_score = bert_info["target_score"]

    candidate_info = bert_info["candidate_scores"].get(candidate)

    if candidate_info is None:
        return None

    candidate_score = candidate_info["candidate_score"]
    relative_score = candidate_info["relative_to_target"]

    # Если BERT сам почти не видит правильный ответ,
    # relative score становится ненадежным.
    if target_score < BERT_MIN_RELIABLE_TARGET_SCORE:
        return None

    if candidate_score >= BERT_MIN_CANDIDATE_SCORE and relative_score > BERT_MAX_RELATIVE_TO_TARGET:
        return "too_plausible_in_bert_context"

    return None


def apply_bert_filter_to_ranked(row) -> List[Dict]:
    """
    Применяет BERT-фильтр к ranked_candidates_cefr.
    """
    result = []

    for item in row["ranked_candidates_cefr"]:
        reason = bert_filter_reason(item, row)

        if reason is None:
            result.append(item)

    return result


def collect_removed_by_bert(row) -> List[Dict]:
    """
    Сохраняет кандидаты, удаленные BERT-фильтром.
    """
    removed = []

    for item in row["ranked_candidates_cefr"]:
        reason = bert_filter_reason(item, row)

        if reason is not None:
            candidate = item["candidate"]
            candidate_info = row["bert_scores"]["candidate_scores"].get(candidate, {})

            removed.append(
                {
                    "candidate": candidate,
                    "reason": reason,
                    "candidate_score": candidate_info.get("candidate_score"),
                    "target_score": candidate_info.get("target_score"),
                    "relative_to_target": candidate_info.get("relative_to_target"),
                    "sources": item["sources"]
                }
            )

    return removed


df["ranked_candidates_bert"] = df.apply(
    apply_bert_filter_to_ranked,
    axis=1
)

df["removed_by_bert_filter"] = df.apply(
    collect_removed_by_bert,
    axis=1
)

df["ranked_candidate_words_bert"] = df["ranked_candidates_bert"].apply(
    lambda ranked: [
        item["candidate"]
        for item in ranked
    ]
)

df[
    [
        "target_clean",
        "ranked_candidate_words_cefr",
        "ranked_candidate_words_bert",
        "removed_by_bert_filter"
    ]
].head(10)

,target_clean,ranked_candidate_words_cefr,ranked_candidate_words_bert,removed_by_bert_filter
0,announced,"[presented, agreed, planned, decided, extended...","[presented, agreed, planned, decided, extended...",[]
1,interested,"[involved, realized]","[involved, realized]",[]
2,however,"[although, therefore, moreover, though, otherw...","[although, therefore, moreover, though, otherw...",[]
3,thick,"[tall, dark, yellow, dry, shiny, rough, gray, ...","[tall, dark, yellow, dry, shiny, rough, gray, ...",[]
4,remind,"[remember, tell, ask, forget, wish, inform, im...","[remember, tell, ask, forget, wish, inform, im...",[]
5,observing,"[monitoring, conducting, analyzing, photograph...","[monitoring, conducting, analyzing, photograph...",[]
6,told,"[spoke, talked, insisted, informed, explained,...","[spoke, talked, insisted, informed, explained,...",[]
7,formed,"[established, joined, created, incorporated, b...","[established, joined, created, incorporated, b...",[]
8,introduced,"[announced, created, modified, used, changed, ...","[announced, created, modified, used, changed, ...",[]
9,attracted,"[garnered, encouraged, generated, grew, grown,...","[garnered, encouraged, generated, grew, grown,...",[]

In [70]:
# =========================
# БЛОК 10.1. Диагностика после BERT-фильтра
# =========================

for _, row in df.head(8).iterrows():
    print("=" * 100)
    print("target:", row["target_clean"])
    print("target_score:", row["bert_scores"]["target_score"])
    print("top before BERT:", row["ranked_candidate_words_cefr"][:8])
    print("top after BERT:", row["ranked_candidate_words_bert"][:8])
    print("removed by BERT:", row["removed_by_bert_filter"][:5])

====================================================================================================
target: announced
target_score: 0.0006681207451038063
top before BERT: ['presented', 'agreed', 'planned', 'decided', 'extended', 'expected', 'unveiled', 'proposed']
top after BERT: ['presented', 'agreed', 'planned', 'decided', 'extended', 'expected', 'unveiled', 'proposed']
removed by BERT: []
====================================================================================================
target: interested
target_score: 2.008183037105482e-05
top before BERT: ['involved', 'realized']
top after BERT: ['involved', 'realized']
removed by BERT: []
====================================================================================================
target: however
target_score: 2.1621238133207044e-09
top before BERT: ['although', 'therefore', 'moreover', 'though', 'otherwise', 'instead']
top after BERT: ['although', 'therefore', 'moreover', 'though', 'otherwise', 'instead']
removed by BERT: []
====================================================================================================
target: thick
target_score: 9.259109035042457e-09
top before BERT: ['tall', 'dark', 'yellow', 'dry', 'shiny', 'rough', 'gray', 'large']
top after BERT: ['tall', 'dark', 'yellow', 'dry', 'shiny', 'rough', 'gray', 'large']
removed by BERT: []
====================================================================================================
target: remind
target_score: 1e-12
top before BERT: ['remember', 'tell', 'ask', 'forget', 'wish', 'inform', 'impress', 'let']
top after BERT: ['remember', 'tell', 'ask', 'forget', 'wish', 'inform', 'impress', 'let']
removed by BERT: []
====================================================================================================
target: observing
target_score: 1.6501070509988836e-09
top before BERT: ['monitoring', 'conducting', 'analyzing', 'photographing', 'witnessing', 'guiding', 'tracking', 'studying']
top after BERT: ['monitoring', 'conducting', 'analyzing', 'photographing', 'witnessing', 'guiding', 'tracking', 'studying']
removed by BERT: []
====================================================================================================
target: told
target_score: 2.372269045736175e-05
top before BERT: ['spoke', 'talked', 'insisted', 'informed', 'explained', 'met', 'acknowledged', 'warned']
top after BERT: ['spoke', 'talked', 'insisted', 'informed', 'explained', 'met', 'acknowledged', 'warned']
removed by BERT: []
====================================================================================================
target: formed
target_score: 2.946823762783879e-08
top before BERT: ['established', 'joined', 'created', 'incorporated', 'became', 'called', 'composed', 'renamed']
top after BERT: ['established', 'joined', 'created', 'incorporated', 'became', 'called', 'composed', 'renamed']
removed by BERT: []

In [73]:
# =========================
# БЛОК 11. Финальный выбор 3 дистракторов
# =========================

FINAL_N = 3


def select_final_distractors_from_ranked(
    ranked_candidates: List[Dict],
    n: int = 3
) -> List[str]:
    """
    Берет первые n кандидатов из финального ranked списка.
    """
    selected = []

    for item in ranked_candidates:
        candidate = clean_text(item["candidate"]).lower()

        if not candidate:
            continue

        if candidate in selected:
            continue

        selected.append(candidate)

        if len(selected) >= n:
            break

    return selected


df["final_distractors"] = df["ranked_candidates_bert"].apply(
    lambda ranked: select_final_distractors_from_ranked(
        ranked,
        n=FINAL_N
    )
)

df["num_final_distractors"] = df["final_distractors"].apply(len)

df[
    [
        "kod",
        "task_id",
        "target_clean",
        "final_distractors",
        "num_final_distractors"
    ]
].head(50)

,kod,task_id,target_clean,final_distractors,num_final_distractors
0,09B13D,30,announced,"[presented, agreed, planned]",3
1,09B13D,31,interested,"[involved, realized]",2
2,09B13D,32,however,"[although, therefore, moreover]",3
3,09B13D,33,thick,"[tall, dark, yellow]",3
4,09B13D,34,remind,"[remember, tell, ask]",3
5,09B13D,35,observing,"[monitoring, conducting, analyzing]",3
6,09B13D,36,told,"[spoke, talked, insisted]",3
7,0EAA8F,32,formed,"[established, joined, created]",3
8,0EAA8F,33,introduced,"[announced, created, modified]",3
9,0EAA8F,34,attracted,"[garnered, encouraged, generated]",3
10,0EAA8F,35,out,"[up, down, over]",3
11,0EAA8F,36,talk,"[tell, say, want]",3
12,0EAA8F,37,discovered,"[unearthed, believed, invented]",3
13,0EAA8F,38,reason,"[thing, idea, sort]",3
14,15e618,30,recognised,"[regarded, established, respected]",3
15,15e618,31,imagine,"[feel, understand, realize]",3
16,15e618,32,tour,"[trip, journey, travel]",3
17,15e618,33,trouble,"[lot, chance, things]",3
18,15e618,34,managed,"[maintained, helped, completed]",3
19,15e618,35,afford,"[provide, allow, pay]",3
20,15e618,36,maintain,"[improve, strengthen, continue]",3
21,1B7697,32,careful,"[thorough, sure, meticulous]",3
22,1B7697,33,reminded,"[remembered, recalled, talked]",3
23,1B7697,34,waiting,"[coming, sitting, leaving]",3
24,1B7697,35,saw,"[brought, turned, started]",3
25,1B7697,36,impressed,"[interested, thrilled, admired]",3
26,1B7697,37,suppose,"[presume, mean, pretend]",3
27,1B7697,38,drop,"[increases, gain, offset]",3
28,204265,32,on,"[for, out, off]",3
29,204265,33,attention,"[addition, criticism, spotlight]",3
30,204265,34,definitely,"[basically, necessarily, hopefully]",3
31,204265,35,bother,"[worry, pretend, guess]",3
32,204265,36,makes,"[turns, looks, seems]",3
33,204265,37,nevertheless,"[although, moreover, therefore]",3
34,204265,38,told,"[spoke, talked, insisted]",3
35,207FE9,32,off,"[away, up, onto]",3
36,207FE9,33,seen,"[turned, shown]",2
37,207FE9,34,brought,"[raised, saw, followed]",3
38,207FE9,35,enjoy,"[prefer, feel, want]",3
39,207FE9,36,mind,"[lot, life, thoughts]",3
40,207FE9,37,point,"[time, difference, end]",3
41,207FE9,38,succeed,"[achieve, replace, manage]",3
42,1234,32,lookes,[],0
43,1234,33,hardly,"[rarely, merely, quite]",3
44,1234,34,on,"[over, into, back]",3
45,1234,35,cheer,"[crowd, cry, shout]",3
46,1234,36,reminded,"[remembered, talked, surprised]",3
47,1234,37,agreement,"[treaty, proposal, compromise]",3
48,1234,38,moreover,"[therefore, however, otherwise]",3
49,1112,32,reach,"[bring, meet, come]",3

In [72]:
# =========================
# БЛОК 11. Диагностика финального выбора
# =========================

for _, row in df.head(20).iterrows():
    print("=" * 100)
    print("kod:", row["kod"], "| task_id:", row["task_id"])
    print("target:", row["target_clean"])
    print("gold:", row["gold_distractors"])
    print("final:", row["final_distractors"])
    print("num:", row["num_final_distractors"])

====================================================================================================
kod: 09B13D | task_id: 30
target: announced
gold: ['promoted', 'extended', 'presented']
final: ['presented', 'agreed', 'planned']
num: 3
====================================================================================================
kod: 09B13D | task_id: 31
target: interested
gold: ['delighted', 'inspired', 'excited']
final: ['involved', 'realized']
num: 2
====================================================================================================
kod: 09B13D | task_id: 32
target: however
gold: ['moreover', 'although', 'otherwise']
final: ['although', 'therefore', 'moreover']
num: 3
====================================================================================================
kod: 09B13D | task_id: 33
target: thick
gold: ['heavy', 'strong', 'rich']
final: ['tall', 'dark', 'yellow']
num: 3
====================================================================================================
kod: 09B13D | task_id: 34
target: remind
gold: ['review', 'remember', 'reflect']
final: ['remember', 'tell', 'ask']
num: 3
====================================================================================================
kod: 09B13D | task_id: 35
target: observing
gold: ['obtaining', 'offending', 'objecting']
final: ['monitoring', 'conducting', 'analyzing']
num: 3
====================================================================================================
kod: 09B13D | task_id: 36
target: told
gold: ['talked', 'spoke', 'said']
final: ['spoke', 'talked', 'insisted']
num: 3
====================================================================================================
kod: 0EAA8F | task_id: 32
target: formed
gold: ['kept', 'held', 'used']
final: ['established', 'joined', 'created']
num: 3
====================================================================================================
kod: 0EAA8F | task_id: 33
target: introduced
gold: ['called', 'greeted', 'met']
final: ['announced', 'created', 'modified']
num: 3
====================================================================================================
kod: 0EAA8F | task_id: 34
target: attracted
gold: ['involved', 'appealed', 'engaged']
final: ['garnered', 'encouraged', 'generated']
num: 3
====================================================================================================
kod: 0EAA8F | task_id: 35
target: out
gold: ['up', 'down', 'on']
final: ['up', 'down', 'over']
num: 3
====================================================================================================
kod: 0EAA8F | task_id: 36
target: talk
gold: ['tell', 'discuss', 'say']
final: ['tell', 'say', 'want']
num: 3
====================================================================================================
kod: 0EAA8F | task_id: 37
target: discovered
gold: ['determined', 'revealed', 'disclosed']
final: ['unearthed', 'believed', 'invented']
num: 3
====================================================================================================
kod: 0EAA8F | task_id: 38
target: reason
gold: ['matter', 'account', 'cause']
final: ['thing', 'idea', 'sort']
num: 3
====================================================================================================
kod: 15e618 | task_id: 30
target: recognised
gold: ['resembled', 'received', 'reviewed']
final: ['regarded', 'established', 'respected']
num: 3
====================================================================================================
kod: 15e618 | task_id: 31
target: imagine
gold: ['visualise', 'invent', 'expect']
final: ['feel', 'understand', 'realize']
num: 3
====================================================================================================
kod: 15e618 | task_id: 32
target: tour
gold: ['travel', 'voyage', 'journey']
final: ['trip', 'journey', 'travel']
num: 3
====================================================================================================
kod: 15e618 | task_id: 33
target: trouble
gold: ['problem', 'fault', 'worry']
final: ['lot', 'chance', 'things']
num: 3
====================================================================================================
kod: 15e618 | task_id: 34
target: managed
gold: ['succeeded', 'fulfilled', 'completed']
final: ['maintained', 'helped', 'completed']
num: 3
====================================================================================================
kod: 15e618 | task_id: 35
target: afford
gold: ['approve', 'arrange', 'allow']
final: ['provide', 'allow', 'pay']
num: 3

In [74]:
# =========================
# БЛОК 12. Метрики совпадения с gold distractors
# =========================

def calculate_gold_overlap(final_distractors: List[str], gold_distractors: List[str]) -> Dict[str, float]:
    """
    Считает совпадение с реальными дистракторами ЕГЭ.

    exact_overlap_count: сколько финальных дистракторов совпало с gold.
    overlap_ratio: доля совпавших из 3.
    """
    final_set = set(
        clean_text(x).lower()
        for x in final_distractors
        if clean_text(x)
    )

    gold_set = set(
        clean_text(x).lower()
        for x in gold_distractors
        if clean_text(x)
    )

    overlap = final_set & gold_set

    return {
        "exact_overlap_count": len(overlap),
        "overlap_ratio": len(overlap) / max(len(gold_set), 1),
        "overlap_items": ", ".join(sorted(overlap))
    }


df["gold_overlap_info"] = df.apply(
    lambda row: calculate_gold_overlap(
        row["final_distractors"],
        row["gold_distractors"]
    ),
    axis=1
)

df["gold_overlap_count"] = df["gold_overlap_info"].apply(
    lambda x: x["exact_overlap_count"]
)

df["gold_overlap_ratio"] = df["gold_overlap_info"].apply(
    lambda x: x["overlap_ratio"]
)

df["gold_overlap_items"] = df["gold_overlap_info"].apply(
    lambda x: x["overlap_items"]
)

print("Среднее число совпадений с gold:", df["gold_overlap_count"].mean())
print("Средняя доля совпадения:", df["gold_overlap_ratio"].mean())

df["gold_overlap_count"].value_counts().sort_index()

Среднее число совпадений с gold: 0.5714285714285714
Средняя доля совпадения: 0.19047619047619047

gold_overlap_count
0    210
1     77
2     49
3      7
Name: count, dtype: int64

In [75]:
# =========================
# БЛОК 12. Подробная финальная таблица
# =========================

final_rows = []

for _, row in df.iterrows():
    result = {
        "item_key": row["item_key"],
        "kod": row["kod"],
        "title": row["title"],
        "task_id": row["task_id"],
        "target": row["target_clean"],
        "target_cefr": get_cefr_level(row["target_clean"]),
        "sentence_with_gap": row["sentence_with_gap_clean"],
        "sentence_with_answer": row["sentence_clean"],
        "gold_distractors": ", ".join(row["gold_distractors"]),
        "final_distractors": ", ".join(row["final_distractors"]),
        "num_final_distractors": row["num_final_distractors"],
        "gold_overlap_count": row["gold_overlap_count"],
        "gold_overlap_ratio": row["gold_overlap_ratio"],
        "gold_overlap_items": row["gold_overlap_items"]
    }

    for i in range(FINAL_N):
        if i < len(row["final_distractors"]):
            candidate = row["final_distractors"][i]

            # Ищем информацию о candidate в ranked_candidates_bert
            candidate_info = None

            for item in row["ranked_candidates_bert"]:
                if item["candidate"] == candidate:
                    candidate_info = item
                    break

            result[f"generated_distractor_{i+1}"] = candidate
            result[f"generated_distractor_{i+1}_cefr"] = get_cefr_level(candidate)

            if candidate_info is not None:
                result[f"generated_distractor_{i+1}_sources"] = ", ".join(candidate_info["sources"])
                result[f"generated_distractor_{i+1}_similarity"] = candidate_info["similarity"]
                result[f"generated_distractor_{i+1}_score"] = candidate_info["final_score"]
            else:
                result[f"generated_distractor_{i+1}_sources"] = ""
                result[f"generated_distractor_{i+1}_similarity"] = None
                result[f"generated_distractor_{i+1}_score"] = None
        else:
            result[f"generated_distractor_{i+1}"] = ""
            result[f"generated_distractor_{i+1}_cefr"] = ""
            result[f"generated_distractor_{i+1}_sources"] = ""
            result[f"generated_distractor_{i+1}_similarity"] = None
            result[f"generated_distractor_{i+1}_score"] = None

    final_rows.append(result)


final_results_df = pd.DataFrame(final_rows)

final_results_df.head()

,item_key,kod,title,task_id,target,target_cefr,sentence_with_gap,sentence_with_answer,gold_distractors,final_distractors,...,generated_distractor_2,generated_distractor_2_cefr,generated_distractor_2_sources,generated_distractor_2_similarity,generated_distractor_2_score,generated_distractor_3,generated_distractor_3_cefr,generated_distractor_3_sources,generated_distractor_3_similarity,generated_distractor_3_score
0,09B13D|Going on a hike|30,09B13D,Going on a hike,30,announced,B1,"Last week, our coach Mr Brown 30 ______ we wer...","Last week, our coach Mr Brown announced we wer...","promoted, extended, presented","presented, agreed, planned",...,agreed,A1,SemanticModel,0.770929,0.820929,planned,A1,SemanticModel,0.748850,0.798850
1,09B13D|Going on a hike|31,09B13D,Going on a hike,31,interested,A1,We weren't all that 31 ______ in the outdoors.,We weren't all that interested in the outdoors.,"delighted, inspired, excited","involved, realized",...,realized,None,SemanticModel,0.603800,0.653800,,,,NaN,NaN
2,09B13D|Going on a hike|32,09B13D,Going on a hike,32,however,A2,"32 ______, Mr Brown claimed that we'd really e...","However, Mr Brown claimed that we'd really enj...","moreover, although, otherwise","although, therefore, moreover",...,therefore,B1,"SemanticModel, LearnerCorpus",0.782361,1.082361,moreover,B1,"SemanticModel, LearnerCorpus",0.769414,1.069414
3,09B13D|Going on a hike|33,09B13D,Going on a hike,33,thick,A1,"Now we were in a state park, marching through ...","Now we were in a state park, marching through ...","heavy, strong, rich","tall, dark, yellow",...,dark,A1,SemanticModel,0.665432,0.715432,yellow,A1,SemanticModel,0.618783,0.668783
4,09B13D|Going on a hike|34,09B13D,Going on a hike,34,remind,A2,Doesn't its shape 34 ______ you of an elephant...,"Doesn't its shape remind you of an elephant?"" ...","review, remember, reflect","remember, tell, ask",...,tell,A1,SemanticModel,0.757472,0.807472,ask,A1,SemanticModel,0.677094,0.727094

In [76]:
# =========================
# БЛОК 12. Диагностическая таблица по всем кандидатам
# =========================

diagnostic_rows = []

for _, row in df.iterrows():
    final_set = set(row["final_distractors"])
    gold_set = set(row["gold_distractors"])

    for item in row["ranked_candidates_bert"]:
        candidate = item["candidate"]

        bert_info = row["bert_scores"]["candidate_scores"].get(
            candidate,
            {}
        )

        diagnostic_rows.append(
            {
                "item_key": row["item_key"],
                "kod": row["kod"],
                "title": row["title"],
                "task_id": row["task_id"],
                "target": row["target_clean"],
                "target_cefr": get_cefr_level(row["target_clean"]),
                "candidate": candidate,
                "candidate_cefr": get_cefr_level(candidate),
                "selected_final": candidate in final_set,
                "in_gold_distractors": candidate in gold_set,
                "sources": ", ".join(item["sources"]),
                "similarity": item["similarity"],
                "source_bonus": item["source_bonus"],
                "penalty": item["penalty"],
                "final_score": item["final_score"],
                "bert_candidate_score": bert_info.get("candidate_score"),
                "bert_target_score": bert_info.get("target_score"),
                "bert_relative_to_target": bert_info.get("relative_to_target")
            }
        )


diagnostic_df = pd.DataFrame(diagnostic_rows)

diagnostic_df.head()

,item_key,kod,title,task_id,target,target_cefr,candidate,candidate_cefr,selected_final,in_gold_distractors,sources,similarity,source_bonus,penalty,final_score,bert_candidate_score,bert_target_score,bert_relative_to_target
0,09B13D|Going on a hike|30,09B13D,Going on a hike,30,announced,B1,presented,A1,True,True,LearnerCorpus,0.610056,0.25,0.0,0.860056,4.550969e-11,0.000668,6.811597e-08
1,09B13D|Going on a hike|30,09B13D,Going on a hike,30,announced,B1,agreed,A1,True,False,SemanticModel,0.770929,0.05,0.0,0.820929,6.241898e-08,0.000668,9.342471e-05
2,09B13D|Going on a hike|30,09B13D,Going on a hike,30,announced,B1,planned,A1,True,False,SemanticModel,0.748850,0.05,0.0,0.798850,4.233681e-09,0.000668,6.336700e-06
3,09B13D|Going on a hike|30,09B13D,Going on a hike,30,announced,B1,decided,A2,False,False,SemanticModel,0.745480,0.05,0.0,0.795480,1.414245e-10,0.000668,2.116750e-07
4,09B13D|Going on a hike|30,09B13D,Going on a hike,30,announced,B1,extended,B1,False,True,LearnerCorpus,0.536892,0.25,0.0,0.786892,4.029006e-11,0.000668,6.030356e-08

In [77]:
# =========================
# БЛОК 12. Сводная статистика
# =========================

summary_overall = pd.DataFrame(
    [
        {
            "metric": "Количество заданий",
            "value": len(final_results_df)
        },
        {
            "metric": "Заданий с 3 дистракторами",
            "value": int((final_results_df["num_final_distractors"] == 3).sum())
        },
        {
            "metric": "Заданий с менее чем 3 дистракторами",
            "value": int((final_results_df["num_final_distractors"] < 3).sum())
        },
        {
            "metric": "Среднее число совпадений с gold",
            "value": float(final_results_df["gold_overlap_count"].mean())
        },
        {
            "metric": "Средняя доля совпадения с gold",
            "value": float(final_results_df["gold_overlap_ratio"].mean())
        }
    ]
)

source_rows = []

for i in range(1, FINAL_N + 1):
    source_col = f"generated_distractor_{i}_sources"

    for value in final_results_df[source_col].dropna():
        for source in str(value).split(","):
            source = source.strip()

            if source:
                source_rows.append(source)

summary_sources = (
    pd.Series(source_rows)
    .value_counts()
    .reset_index()
)

summary_sources.columns = [
    "source",
    "count"
]

cefr_rows = []

for i in range(1, FINAL_N + 1):
    cefr_col = f"generated_distractor_{i}_cefr"

    cefr_rows.extend(
        final_results_df[cefr_col]
        .replace("", pd.NA)
        .dropna()
        .tolist()
    )

summary_cefr = (
    pd.Series(cefr_rows)
    .value_counts()
    .reset_index()
)

summary_cefr.columns = [
    "cefr_level",
    "count"
]

print(summary_overall)
print(summary_sources)
print(summary_cefr)

                                metric       value
0                   Количество заданий  343.000000
1            Заданий с 3 дистракторами  325.000000
2  Заданий с менее чем 3 дистракторами   18.000000
3      Среднее число совпадений с gold    0.571429
4       Средняя доля совпадения с gold    0.190476
          source  count
0  SemanticModel    902
1  LearnerCorpus    291
  cefr_level  count
0         A1    443
1         A2    235
2         B1    208
3         B2     46

In [ ]:
                           metric       value
0                   Количество заданий  490.000000
1            Заданий с 3 дистракторами  472.000000
2  Заданий с менее чем 3 дистракторами   18.000000
3      Среднее число совпадений с gold    0.571429
4       Средняя доля совпадения с gold    0.190476
          source  count
0  SemanticModel    830
1  LearnerCorpus    363
  cefr_level  count
0         A1    443
1         A2    235
2         B1    208
3         B2     46

In [78]:
# =========================
# БЛОК 12. Экспорт результатов
# =========================

final_results_df.to_excel(
    "ege_generated_distractors_final.xlsx",
    index=False
)

diagnostic_df.to_excel(
    "ege_distractors_diagnostics_final.xlsx",
    index=False
)

with pd.ExcelWriter("ege_distractors_summary_final.xlsx") as writer:
    summary_overall.to_excel(
        writer,
        sheet_name="overall",
        index=False
    )

    summary_sources.to_excel(
        writer,
        sheet_name="sources",
        index=False
    )

    summary_cefr.to_excel(
        writer,
        sheet_name="cefr",
        index=False
    )

print("Файлы сохранены:")
print("ege_generated_distractors_final.xlsx")
print("ege_distractors_diagnostics_final.xlsx")
print("ege_distractors_summary_final.xlsx")

Файлы сохранены:
ege_generated_distractors_final.xlsx
ege_distractors_diagnostics_final.xlsx
ege_distractors_summary_final.xlsx

In [ ]:
# =========================
# БЛОК 12. Скачать файлы из Colab
# =========================

from google.colab import files

files.download("ege_generated_distractors_final.xlsx")
files.download("ege_distractors_diagnostics_final.xlsx")
files.download("ege_distractors_summary_final.xlsx")